set_property SRC_FILE_INFO {cfile:C:/Vulcan/Design_Tool/Vivado/VC707/breath_led/breath_led.srcs/constrs_1/new/pwm_constraints.xdc rfile:../../../breath_led.srcs/constrs_1/new/pwm_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM39 [get_ports led]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR40 [get_ports rst_n]
