-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_v_vcresampler_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_out_hresampled_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_out_hresampled_empty_n : IN STD_LOGIC;
    stream_out_hresampled_read : OUT STD_LOGIC;
    height_val7_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    height_val7_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_empty_n : IN STD_LOGIC;
    height_val7_read : OUT STD_LOGIC;
    width_val12_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val12_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_empty_n : IN STD_LOGIC;
    width_val12_read : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_vresampled_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_vresampled_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_out_vresampled_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_out_vresampled_full_n : IN STD_LOGIC;
    stream_out_vresampled_write : OUT STD_LOGIC;
    height_val7_c_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    height_val7_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_c_full_n : IN STD_LOGIC;
    height_val7_c_write : OUT STD_LOGIC;
    width_val12_c_din : OUT STD_LOGIC_VECTOR (12 downto 0);
    width_val12_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_c_full_n : IN STD_LOGIC;
    width_val12_c_write : OUT STD_LOGIC );
end;


architecture behav of design_1_v_tpg_0_0_v_vcresampler_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal height_val7_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal width_val12_blk_n : STD_LOGIC;
    signal height_val7_c_blk_n : STD_LOGIC;
    signal width_val12_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal loopWidth_reg_279 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal height_val7_read_reg_284 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln2232_fu_180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln2232_reg_289 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopHeight_fu_184_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopHeight_reg_294 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_77_fu_213_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_77_reg_302 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal cmp33_i_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp33_i_reg_307 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp107_i_fu_222_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp107_i_reg_312 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_317 : STD_LOGIC_VECTOR (0 downto 0);
    signal linebuf_y_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_c_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal linebuf_c_1_q1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_idle : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_ready : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce0 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_we0 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce1 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_ce0 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_we0 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce0 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_we0 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address1 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce1 : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal p_0_0324493_lcssa516_i_fu_86 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0335491_lcssa513_i_fu_82 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_0_2_0_0_0_load489_lcssa510_i_fu_78 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_0_1_0_0_0_load487_lcssa507_i_fu_74 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_0_0_0_0_0_load485_lcssa504_i_fu_70 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_90 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln2272_fu_202_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln2272_fu_197_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal yOffset_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln2272_fu_193_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_y_fu_208_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        stream_out_hresampled_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_out_hresampled_empty_n : IN STD_LOGIC;
        stream_out_hresampled_read : OUT STD_LOGIC;
        stream_out_vresampled_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_vresampled_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_out_vresampled_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_out_vresampled_full_n : IN STD_LOGIC;
        stream_out_vresampled_write : OUT STD_LOGIC;
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp33_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp107_i : IN STD_LOGIC_VECTOR (0 downto 0);
        linebuf_c_1_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        linebuf_c_1_ce0 : OUT STD_LOGIC;
        linebuf_c_1_we0 : OUT STD_LOGIC;
        linebuf_c_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_c_1_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        linebuf_c_1_ce1 : OUT STD_LOGIC;
        linebuf_c_1_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        empty_40 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0);
        linebuf_y_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        linebuf_y_ce0 : OUT STD_LOGIC;
        linebuf_y_we0 : OUT STD_LOGIC;
        linebuf_y_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_y_q0 : IN STD_LOGIC_VECTOR (7 downto 0);
        linebuf_c_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
        linebuf_c_ce0 : OUT STD_LOGIC;
        linebuf_c_we0 : OUT STD_LOGIC;
        linebuf_c_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        linebuf_c_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
        linebuf_c_ce1 : OUT STD_LOGIC;
        linebuf_c_q1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0324492_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0324492_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0324492_i_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0335490_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0335490_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0335490_i_out_o_ap_vld : OUT STD_LOGIC;
        pix_0_2_0_0_0_load488_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        pix_0_2_0_0_0_load488_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        pix_0_2_0_0_0_load488_i_out_o_ap_vld : OUT STD_LOGIC;
        pix_0_1_0_0_0_load486_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        pix_0_1_0_0_0_load486_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        pix_0_1_0_0_0_load486_i_out_o_ap_vld : OUT STD_LOGIC;
        pix_0_0_0_0_0_load484_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        pix_0_0_0_0_0_load484_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        pix_0_0_0_0_0_load484_i_out_o_ap_vld : OUT STD_LOGIC );
    end component;


    component design_1_v_tpg_0_0_v_vcresampler_core_linebuf_y_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component design_1_v_tpg_0_0_v_vcresampler_core_linebuf_c_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    linebuf_y_U : component design_1_v_tpg_0_0_v_vcresampler_core_linebuf_y_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_address0,
        ce0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_ce0,
        we0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_we0,
        d0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_d0,
        q0 => linebuf_y_q0);

    linebuf_c_U : component design_1_v_tpg_0_0_v_vcresampler_core_linebuf_c_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address0,
        ce0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce0,
        we0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_we0,
        d0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_d0,
        address1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address1,
        ce1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce1,
        q1 => linebuf_c_q1);

    linebuf_c_1_U : component design_1_v_tpg_0_0_v_vcresampler_core_linebuf_c_RAM_AUTO_1R1W
    generic map (
        DataWidth => 8,
        AddressRange => 4096,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address0,
        ce0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce0,
        we0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_we0,
        d0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_d0,
        address1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address1,
        ce1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce1,
        q1 => linebuf_c_1_q1);

    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138 : component design_1_v_tpg_0_0_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start,
        ap_done => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done,
        ap_idle => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_idle,
        ap_ready => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_ready,
        stream_out_hresampled_dout => stream_out_hresampled_dout,
        stream_out_hresampled_num_data_valid => ap_const_lv3_0,
        stream_out_hresampled_fifo_cap => ap_const_lv3_0,
        stream_out_hresampled_empty_n => stream_out_hresampled_empty_n,
        stream_out_hresampled_read => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read,
        stream_out_vresampled_din => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_din,
        stream_out_vresampled_num_data_valid => ap_const_lv3_0,
        stream_out_vresampled_fifo_cap => ap_const_lv3_0,
        stream_out_vresampled_full_n => stream_out_vresampled_full_n,
        stream_out_vresampled_write => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write,
        loopWidth => loopWidth_reg_279,
        p_read => p_read,
        cmp33_i => cmp33_i_reg_307,
        cmp107_i => cmp107_i_reg_312,
        linebuf_c_1_address0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address0,
        linebuf_c_1_ce0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce0,
        linebuf_c_1_we0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_we0,
        linebuf_c_1_d0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_d0,
        linebuf_c_1_address1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address1,
        linebuf_c_1_ce1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce1,
        linebuf_c_1_q1 => linebuf_c_1_q1,
        empty_40 => empty_77_reg_302,
        empty => tmp_reg_317,
        linebuf_y_address0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_address0,
        linebuf_y_ce0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_ce0,
        linebuf_y_we0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_we0,
        linebuf_y_d0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_d0,
        linebuf_y_q0 => linebuf_y_q0,
        linebuf_c_address0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address0,
        linebuf_c_ce0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce0,
        linebuf_c_we0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_we0,
        linebuf_c_d0 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_d0,
        linebuf_c_address1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address1,
        linebuf_c_ce1 => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce1,
        linebuf_c_q1 => linebuf_c_q1,
        p_0_0324492_i_out_i => p_0_0324493_lcssa516_i_fu_86,
        p_0_0324492_i_out_o => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o,
        p_0_0324492_i_out_o_ap_vld => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o_ap_vld,
        p_0_0335490_i_out_i => p_0_0335491_lcssa513_i_fu_82,
        p_0_0335490_i_out_o => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o,
        p_0_0335490_i_out_o_ap_vld => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o_ap_vld,
        pix_0_2_0_0_0_load488_i_out_i => pix_0_2_0_0_0_load489_lcssa510_i_fu_78,
        pix_0_2_0_0_0_load488_i_out_o => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o,
        pix_0_2_0_0_0_load488_i_out_o_ap_vld => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o_ap_vld,
        pix_0_1_0_0_0_load486_i_out_i => pix_0_1_0_0_0_load487_lcssa507_i_fu_74,
        pix_0_1_0_0_0_load486_i_out_o => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o,
        pix_0_1_0_0_0_load486_i_out_o_ap_vld => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o_ap_vld,
        pix_0_0_0_0_0_load484_i_out_i => pix_0_0_0_0_0_load485_lcssa504_i_fu_70,
        pix_0_0_0_0_0_load484_i_out_o => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o,
        pix_0_0_0_0_0_load484_i_out_o_ap_vld => grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln2272_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_ready = ap_const_logic_1)) then 
                    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_90_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_90 <= ap_const_lv15_0;
            elsif (((icmp_ln2272_fu_197_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                y_fu_90 <= add_ln2272_fu_202_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                cmp107_i_reg_312 <= cmp107_i_fu_222_p2;
                cmp33_i_reg_307 <= cmp33_i_fu_217_p2;
                empty_77_reg_302 <= empty_77_fu_213_p1;
                tmp_reg_317 <= out_y_fu_208_p2(15 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                height_val7_read_reg_284 <= height_val7_dout;
                loopHeight_reg_294 <= loopHeight_fu_184_p2;
                loopWidth_reg_279 <= width_val12_dout;
                    zext_ln2232_reg_289(0) <= zext_ln2232_fu_180_p1(0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0324493_lcssa516_i_fu_86 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o_ap_vld = ap_const_logic_1))) then
                p_0_0335491_lcssa513_i_fu_82 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                pix_0_0_0_0_0_load485_lcssa504_i_fu_70 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o_ap_vld = ap_const_logic_1))) then
                pix_0_1_0_0_0_load487_lcssa507_i_fu_74 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o_ap_vld = ap_const_logic_1))) then
                pix_0_2_0_0_0_load489_lcssa510_i_fu_78 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o;
            end if;
        end if;
    end process;
    zext_ln2232_reg_289(15 downto 1) <= "000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_block_state1, ap_block_state2, ap_CS_fsm_state3, grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done, ap_CS_fsm_state5, icmp_ln2272_fu_197_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln2272_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln2272_fu_202_p2 <= std_logic_vector(unsigned(y_fu_90) + unsigned(ap_const_lv15_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(ap_block_state2)
    begin
        if ((ap_const_boolean_1 = ap_block_state2)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done)
    begin
        if ((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state2_assign_proc : process(height_val7_empty_n, width_val12_empty_n, height_val7_c_full_n, width_val12_c_full_n)
    begin
                ap_block_state2 <= ((width_val12_c_full_n = ap_const_logic_0) or (height_val7_c_full_n = ap_const_logic_0) or (width_val12_empty_n = ap_const_logic_0) or (height_val7_empty_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln2272_fu_197_p2)
    begin
        if (((icmp_ln2272_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln2272_fu_197_p2)
    begin
        if (((icmp_ln2272_fu_197_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp107_i_fu_222_p2 <= "0" when (y_fu_90 = ap_const_lv15_0) else "1";
    cmp33_i_fu_217_p2 <= "1" when (unsigned(zext_ln2272_fu_193_p1) < unsigned(height_val7_read_reg_284)) else "0";
    empty_77_fu_213_p1 <= out_y_fu_208_p2(1 - 1 downto 0);
    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg;

    height_val7_blk_n_assign_proc : process(height_val7_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            height_val7_blk_n <= height_val7_empty_n;
        else 
            height_val7_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_val7_c_blk_n_assign_proc : process(height_val7_c_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            height_val7_c_blk_n <= height_val7_c_full_n;
        else 
            height_val7_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val7_c_din <= height_val7_dout(12 - 1 downto 0);

    height_val7_c_write_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            height_val7_c_write <= ap_const_logic_1;
        else 
            height_val7_c_write <= ap_const_logic_0;
        end if; 
    end process;


    height_val7_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            height_val7_read <= ap_const_logic_1;
        else 
            height_val7_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln2272_fu_197_p2 <= "1" when (signed(zext_ln2272_fu_193_p1) < signed(loopHeight_reg_294)) else "0";
    loopHeight_fu_184_p2 <= std_logic_vector(unsigned(height_val7_dout) + unsigned(zext_ln2232_fu_180_p1));
    out_y_fu_208_p2 <= std_logic_vector(unsigned(zext_ln2272_fu_193_p1) - unsigned(zext_ln2232_reg_289));

    stream_out_hresampled_read_assign_proc : process(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            stream_out_hresampled_read <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read;
        else 
            stream_out_hresampled_read <= ap_const_logic_0;
        end if; 
    end process;

    stream_out_vresampled_din <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_din;

    stream_out_vresampled_write_assign_proc : process(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            stream_out_vresampled_write <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write;
        else 
            stream_out_vresampled_write <= ap_const_logic_0;
        end if; 
    end process;


    width_val12_blk_n_assign_proc : process(width_val12_empty_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            width_val12_blk_n <= width_val12_empty_n;
        else 
            width_val12_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_val12_c_blk_n_assign_proc : process(width_val12_c_full_n, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            width_val12_c_blk_n <= width_val12_c_full_n;
        else 
            width_val12_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val12_c_din <= width_val12_dout(13 - 1 downto 0);

    width_val12_c_write_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            width_val12_c_write <= ap_const_logic_1;
        else 
            width_val12_c_write <= ap_const_logic_0;
        end if; 
    end process;


    width_val12_read_assign_proc : process(ap_CS_fsm_state2, ap_block_state2)
    begin
        if (((ap_const_boolean_0 = ap_block_state2) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            width_val12_read <= ap_const_logic_1;
        else 
            width_val12_read <= ap_const_logic_0;
        end if; 
    end process;

    yOffset_fu_175_p2 <= (p_read xor ap_const_lv1_1);
    zext_ln2232_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(yOffset_fu_175_p2),16));
    zext_ln2272_fu_193_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_90),16));
end behav;
