-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0);
    patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    dpYUVCoef_val : IN STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    height_val7_c21_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    height_val7_c21_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_c21_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_c21_full_n : IN STD_LOGIC;
    height_val7_c21_write : OUT STD_LOGIC;
    width_val12_c24_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    width_val12_c24_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_c24_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_c24_full_n : IN STD_LOGIC;
    width_val12_c24_write : OUT STD_LOGIC;
    motionSpeed_val19_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val19_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val19_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val19_c_full_n : IN STD_LOGIC;
    motionSpeed_val19_c_write : OUT STD_LOGIC;
    s : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of design_1_v_tpg_0_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv14_7 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000111";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv14_F : STD_LOGIC_VECTOR (13 downto 0) := "00000000001111";
    constant ap_const_lv10_3FF : STD_LOGIC_VECTOR (9 downto 0) := "1111111111";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv17_1FFFF : STD_LOGIC_VECTOR (16 downto 0) := "11111111111111111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal hdata : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal rampVal_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal height_val7_c21_blk_n : STD_LOGIC;
    signal width_val12_c24_blk_n : STD_LOGIC;
    signal motionSpeed_val19_c_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal rampStart_load_reg_1071 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidth_reg_1077 : STD_LOGIC_VECTOR (10 downto 0);
    signal empty_109_fu_573_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_109_reg_1083 : STD_LOGIC_VECTOR (7 downto 0);
    signal barWidthMinSamples_fu_593_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal barWidthMinSamples_reg_1088 : STD_LOGIC_VECTOR (9 downto 0);
    signal shl_i_fu_613_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_i_reg_1093 : STD_LOGIC_VECTOR (15 downto 0);
    signal sub_i_i_i_fu_635_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_i_i_i_reg_1098 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub35_i_fu_641_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub35_i_reg_1103 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub10_i_fu_647_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub10_i_reg_1108 : STD_LOGIC_VECTOR (16 downto 0);
    signal cmp121_i_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp121_i_reg_1113 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_4_reg_1118 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp_i287_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp_i287_reg_1127 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_fu_824_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_1132 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp11_i_fu_830_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp11_i_reg_1137 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_111_fu_835_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_111_reg_1142 : STD_LOGIC_VECTOR (7 downto 0);
    signal Sel_reg_1147 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1_ap_vld : STD_LOGIC;
    signal ap_phi_mux_rampVal_3_flag_0_phi_fu_372_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_3_flag_0_reg_368 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_phi_mux_hdata_flag_0_phi_fu_384_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal hdata_flag_0_reg_380 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_rampVal_2_flag_0_phi_fu_396_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal rampVal_2_flag_0_reg_392 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal rampVal_3_new_0_fu_274 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_3_loc_0_fu_270 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal rampVal_loc_0_fu_266 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal hBarSel_4_0_loc_0_fu_262 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal zonePlateVAddr_loc_0_fu_258 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_loc_0_fu_254 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_0_loc_0_fu_250 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hdata_new_0_fu_246 : STD_LOGIC_VECTOR (15 downto 0);
    signal hdata_loc_0_fu_242 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_2_loc_0_fu_238 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_3_0_loc_0_fu_234 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal rampVal_2_new_0_fu_230 : STD_LOGIC_VECTOR (15 downto 0);
    signal rampVal_2_loc_0_fu_226 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal vBarSel_3_loc_0_fu_222 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal hBarSel_5_0_loc_0_fu_218 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_2_0_0_0218_lcssa227_fu_210 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0216_lcssa224_fu_206 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_0_0_0_0214_lcssa221_fu_202 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln750_fu_845_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln563_fu_799_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal y_fu_214 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal add_ln563_fu_804_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln563_fu_727_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1775_fu_719_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1664_fu_707_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1545_fu_691_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1412_fu_683_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln1257_fu_667_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal empty_fu_553_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_i_fu_557_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal add2_i_fu_577_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_cast_fu_583_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_110_fu_603_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add5_i_fu_607_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_3_fu_621_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal barHeight_cast_fu_631_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal width_val_cast14_fu_549_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal height_val_cast15_fu_599_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln563_1_fu_814_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln563_fu_810_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        rampVal_3_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_0 : IN STD_LOGIC_VECTOR (0 downto 0);
        width_val : IN STD_LOGIC_VECTOR (15 downto 0);
        rampStart_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
        conv2_i_i10_i233_cast : IN STD_LOGIC_VECTOR (7 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        empty_41 : IN STD_LOGIC_VECTOR (7 downto 0);
        barWidth_cast : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidth : IN STD_LOGIC_VECTOR (10 downto 0);
        shl_i : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        sub_i_i_i : IN STD_LOGIC_VECTOR (10 downto 0);
        barWidthMinSamples : IN STD_LOGIC_VECTOR (9 downto 0);
        cmp11_i : IN STD_LOGIC_VECTOR (0 downto 0);
        cmp_i287 : IN STD_LOGIC_VECTOR (0 downto 0);
        sub35_i : IN STD_LOGIC_VECTOR (16 downto 0);
        empty : IN STD_LOGIC_VECTOR (7 downto 0);
        zext_ln565 : IN STD_LOGIC_VECTOR (1 downto 0);
        cmp121_i : IN STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_3_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_3_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hdata_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        hdata_flag_1_out_ap_vld : OUT STD_LOGIC;
        hdata_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_new_1_out_ap_vld : OUT STD_LOGIC;
        hdata_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        hdata_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_2_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_3_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        rampVal_2_flag_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        rampVal_2_flag_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_new_1_out : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_new_1_out_ap_vld : OUT STD_LOGIC;
        rampVal_2_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        rampVal_2_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        vBarSel_3_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_3_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0_loc_1_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_5_0_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0217_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0217_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0217_out_o_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0215_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0215_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0215_out_o_ap_vld : OUT STD_LOGIC;
        p_0_0_0_0_0213_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0213_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0213_out_o_ap_vld : OUT STD_LOGIC;
        rampVal : OUT STD_LOGIC_VECTOR (7 downto 0);
        rampVal_ap_vld : OUT STD_LOGIC;
        hBarSel_4_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        hBarSel_4_0_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC;
        hBarSel_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_0_ap_vld : OUT STD_LOGIC;
        vBarSel : OUT STD_LOGIC_VECTOR (2 downto 0);
        vBarSel_ap_vld : OUT STD_LOGIC;
        hBarSel_3_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_3_0_ap_vld : OUT STD_LOGIC;
        vBarSel_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
        vBarSel_2_ap_vld : OUT STD_LOGIC;
        hBarSel_5_0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        hBarSel_5_0_ap_vld : OUT STD_LOGIC;
        vBarSel_1 : OUT STD_LOGIC_VECTOR (0 downto 0);
        vBarSel_1_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404 : component design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_ready,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_din,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write,
        rampVal_3_flag_0 => rampVal_3_flag_0_reg_368,
        hdata_flag_0 => hdata_flag_0_reg_380,
        rampVal_2_flag_0 => rampVal_2_flag_0_reg_392,
        width_val => width_val,
        rampStart_1 => rampStart_load_reg_1071,
        ZplateHorContStart_val => ZplateHorContStart_val,
        patternId_val => patternId_val,
        conv2_i_i10_i233_cast => rampStart_load_reg_1071,
        y => y_4_reg_1118,
        empty_41 => empty_109_reg_1083,
        barWidth_cast => barWidth_reg_1077,
        barWidth => barWidth_reg_1077,
        shl_i => shl_i_reg_1093,
        ZplateHorContDelta_val => ZplateHorContDelta_val,
        ZplateVerContStart_val => ZplateVerContStart_val,
        cmp12_i => cmp12_i_reg_1132,
        ZplateVerContDelta_val => ZplateVerContDelta_val,
        sub_i_i_i => sub_i_i_i_reg_1098,
        barWidthMinSamples => barWidthMinSamples_reg_1088,
        cmp11_i => cmp11_i_reg_1137,
        cmp_i287 => cmp_i287_reg_1127,
        sub35_i => sub35_i_reg_1103,
        empty => empty_111_reg_1142,
        zext_ln565 => Sel_reg_1147,
        cmp121_i => cmp121_i_reg_1113,
        rampVal_3_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out,
        rampVal_3_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out_ap_vld,
        rampVal_3_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out,
        rampVal_3_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out_ap_vld,
        rampVal_3_loc_1_out_i => rampVal_3_loc_0_fu_270,
        rampVal_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o,
        rampVal_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o_ap_vld,
        rampVal_loc_1_out_i => rampVal_loc_0_fu_266,
        rampVal_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o,
        rampVal_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o_ap_vld,
        hBarSel_4_0_loc_1_out_i => hBarSel_4_0_loc_0_fu_262,
        hBarSel_4_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o,
        hBarSel_4_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o_ap_vld,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_258,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o_ap_vld,
        vBarSel_loc_1_out_i => vBarSel_loc_0_fu_254,
        vBarSel_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o,
        vBarSel_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o_ap_vld,
        hBarSel_0_loc_1_out_i => hBarSel_0_loc_0_fu_250,
        hBarSel_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o,
        hBarSel_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o_ap_vld,
        hdata_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out,
        hdata_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out_ap_vld,
        hdata_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out,
        hdata_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out_ap_vld,
        hdata_loc_1_out_i => hdata_loc_0_fu_242,
        hdata_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o,
        hdata_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o_ap_vld,
        vBarSel_2_loc_1_out_i => vBarSel_2_loc_0_fu_238,
        vBarSel_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o,
        vBarSel_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o_ap_vld,
        hBarSel_3_0_loc_1_out_i => hBarSel_3_0_loc_0_fu_234,
        hBarSel_3_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o,
        hBarSel_3_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o_ap_vld,
        rampVal_2_flag_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out,
        rampVal_2_flag_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out_ap_vld,
        rampVal_2_new_1_out => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out,
        rampVal_2_new_1_out_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out_ap_vld,
        rampVal_2_loc_1_out_i => rampVal_2_loc_0_fu_226,
        rampVal_2_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o,
        rampVal_2_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o_ap_vld,
        vBarSel_3_loc_1_out_i => vBarSel_3_loc_0_fu_222,
        vBarSel_3_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o,
        vBarSel_3_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o_ap_vld,
        hBarSel_5_0_loc_1_out_i => hBarSel_5_0_loc_0_fu_218,
        hBarSel_5_0_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o,
        hBarSel_5_0_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o_ap_vld,
        p_0_2_0_0_0217_out_i => p_0_2_0_0_0218_lcssa227_fu_210,
        p_0_2_0_0_0217_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o,
        p_0_2_0_0_0217_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o_ap_vld,
        p_0_1_0_0_0215_out_i => p_0_1_0_0_0216_lcssa224_fu_206,
        p_0_1_0_0_0215_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o,
        p_0_1_0_0_0215_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o_ap_vld,
        p_0_0_0_0_0213_out_i => p_0_0_0_0_0214_lcssa221_fu_202,
        p_0_0_0_0_0213_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o,
        p_0_0_0_0_0213_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o_ap_vld,
        rampVal => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal,
        rampVal_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_ap_vld,
        hBarSel_4_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0,
        hBarSel_4_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_ap_vld,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_ap_vld,
        hBarSel_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0,
        hBarSel_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_ap_vld,
        vBarSel => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel,
        vBarSel_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_ap_vld,
        hBarSel_3_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0,
        hBarSel_3_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_ap_vld,
        vBarSel_2 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2,
        vBarSel_2_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_ap_vld,
        hBarSel_5_0 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0,
        hBarSel_5_0_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_ap_vld,
        vBarSel_1 => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1,
        vBarSel_1_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    hBarSel_0_loc_0_fu_250_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_0_loc_0_fu_250 <= zext_ln1545_fu_691_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_0_loc_0_fu_250 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_3_0_loc_0_fu_234_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_3_0_loc_0_fu_234 <= zext_ln1664_fu_707_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_3_0_loc_0_fu_234 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_4_0_loc_0_fu_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_4_0_loc_0_fu_262 <= hBarSel_4_0;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_4_0_loc_0_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hBarSel_5_0_loc_0_fu_218_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hBarSel_5_0_loc_0_fu_218 <= zext_ln563_fu_727_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hBarSel_5_0_loc_0_fu_218 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o;
            end if; 
        end if;
    end process;

    hdata_flag_0_reg_380_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                hdata_flag_0_reg_380 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_flag_0_reg_380 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    hdata_loc_0_fu_242_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                hdata_loc_0_fu_242 <= hdata;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                hdata_loc_0_fu_242 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_2_flag_0_reg_392_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_2_flag_0_reg_392 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_flag_0_reg_392 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_2_loc_0_fu_226_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_2_loc_0_fu_226 <= rampVal_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                rampVal_2_loc_0_fu_226 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_3_flag_0_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                rampVal_3_flag_0_reg_368 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out;
            elsif (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_flag_0_reg_368 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    rampVal_3_loc_0_fu_270_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_3_loc_0_fu_270 <= rampVal_1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o_ap_vld = ap_const_logic_1))) then 
                rampVal_3_loc_0_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    rampVal_loc_0_fu_266_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                rampVal_loc_0_fu_266 <= zext_ln1257_fu_667_p1;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o_ap_vld = ap_const_logic_1))) then 
                rampVal_loc_0_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_2_loc_0_fu_238_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_2_loc_0_fu_238 <= vBarSel_2;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_2_loc_0_fu_238 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_3_loc_0_fu_222_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_3_loc_0_fu_222 <= zext_ln1775_fu_719_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_3_loc_0_fu_222 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o;
            end if; 
        end if;
    end process;

    vBarSel_loc_0_fu_254_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                vBarSel_loc_0_fu_254 <= zext_ln1412_fu_683_p1;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                vBarSel_loc_0_fu_254 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o;
            end if; 
        end if;
    end process;

    y_fu_214_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_214 <= ap_const_lv16_0;
            elsif (((icmp_ln563_fu_799_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                y_fu_214 <= add_ln563_fu_804_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_258_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_258 <= zonePlateVAddr;
            elsif (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                zonePlateVAddr_loc_0_fu_258 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                Sel_reg_1147 <= y_4_reg_1118(7 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                barWidthMinSamples_reg_1088 <= barWidthMinSamples_fu_593_p2;
                barWidth_reg_1077 <= add_i_fu_557_p2(13 downto 3);
                cmp121_i_reg_1113 <= cmp121_i_fu_653_p2;
                empty_109_reg_1083 <= empty_109_fu_573_p1;
                rampStart_load_reg_1071 <= rampStart;
                    shl_i_reg_1093(15 downto 8) <= shl_i_fu_613_p3(15 downto 8);
                sub10_i_reg_1108 <= sub10_i_fu_647_p2;
                sub35_i_reg_1103 <= sub35_i_fu_641_p2;
                sub_i_i_i_reg_1098 <= sub_i_i_i_fu_635_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp11_i_reg_1137 <= cmp11_i_fu_830_p2;
                cmp12_i_reg_1132 <= cmp12_i_fu_824_p2;
                cmp_i287_reg_1127 <= cmp_i287_fu_818_p2;
                empty_111_reg_1142 <= empty_111_fu_835_p2;
                y_4_reg_1118 <= y_fu_214;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_phi_mux_hdata_flag_0_phi_fu_384_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                hdata <= hdata_new_0_fu_246;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                hdata_new_0_fu_246 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_0_0_0_0214_lcssa221_fu_202 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_1_0_0_0216_lcssa224_fu_206 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                p_0_2_0_0_0218_lcssa227_fu_210 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampStart <= add_ln750_fu_845_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_3_flag_0_phi_fu_372_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_1 <= rampVal_3_new_0_fu_274;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_phi_mux_rampVal_2_flag_0_phi_fu_396_p4 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                rampVal_2 <= rampVal_2_new_0_fu_230;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                rampVal_2_new_0_fu_230 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out_ap_vld = ap_const_logic_1))) then
                rampVal_3_new_0_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr;
            end if;
        end if;
    end process;
    shl_i_reg_1093(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done, ap_CS_fsm_state4, icmp_ln563_fu_799_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add2_i_fu_577_p2 <= std_logic_vector(unsigned(empty_fu_553_p1) + unsigned(ap_const_lv14_F));
    add5_i_fu_607_p2 <= std_logic_vector(unsigned(empty_110_fu_603_p1) + unsigned(ap_const_lv14_F));
    add_i_fu_557_p2 <= std_logic_vector(unsigned(empty_fu_553_p1) + unsigned(ap_const_lv14_7));
    add_ln563_fu_804_p2 <= std_logic_vector(unsigned(y_fu_214) + unsigned(ap_const_lv16_1));
    add_ln750_fu_845_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(motionSpeed_val));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val7_c21_full_n, width_val12_c24_full_n, motionSpeed_val19_c_full_n)
    begin
                ap_block_state1 <= ((motionSpeed_val19_c_full_n = ap_const_logic_0) or (width_val12_c24_full_n = ap_const_logic_0) or (height_val7_c21_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln563_fu_799_p2)
    begin
        if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_mux_hdata_flag_0_phi_fu_384_p4 <= hdata_flag_0_reg_380;
    ap_phi_mux_rampVal_2_flag_0_phi_fu_396_p4 <= rampVal_2_flag_0_reg_392;
    ap_phi_mux_rampVal_3_flag_0_phi_fu_372_p4 <= rampVal_3_flag_0_reg_368;

    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln563_fu_799_p2)
    begin
        if (((icmp_ln563_fu_799_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    barHeight_cast_fu_631_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_621_p4),11));
    barWidthMinSamples_fu_593_p2 <= std_logic_vector(unsigned(p_cast_fu_583_p4) + unsigned(ap_const_lv10_3FF));
    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_din;

    bckgndYUV_write_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write;
        else 
            bckgndYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    cmp11_i_fu_830_p2 <= "1" when (sub10_i_reg_1108 = zext_ln563_1_fu_814_p1) else "0";
    cmp121_i_fu_653_p2 <= "1" when (dpYUVCoef_val = ap_const_lv8_0) else "0";
    cmp12_i_fu_824_p2 <= "0" when (y_fu_214 = ap_const_lv16_0) else "1";
    cmp_i287_fu_818_p2 <= "1" when (y_fu_214 = ap_const_lv16_0) else "0";
    empty_109_fu_573_p1 <= s(8 - 1 downto 0);
    empty_110_fu_603_p1 <= height_val(14 - 1 downto 0);
    empty_111_fu_835_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(trunc_ln563_fu_810_p1));
    empty_fu_553_p1 <= width_val(14 - 1 downto 0);
    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg;

    height_val7_c21_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val7_c21_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val7_c21_blk_n <= height_val7_c21_full_n;
        else 
            height_val7_c21_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val7_c21_din <= height_val;

    height_val7_c21_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val7_c21_write <= ap_const_logic_1;
        else 
            height_val7_c21_write <= ap_const_logic_0;
        end if; 
    end process;

    height_val_cast15_fu_599_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(height_val),17));
    icmp_ln563_fu_799_p2 <= "1" when (y_fu_214 = height_val) else "0";

    motionSpeed_val19_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, motionSpeed_val19_c_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val19_c_blk_n <= motionSpeed_val19_c_full_n;
        else 
            motionSpeed_val19_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    motionSpeed_val19_c_din <= motionSpeed_val;

    motionSpeed_val19_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val19_c_write <= ap_const_logic_1;
        else 
            motionSpeed_val19_c_write <= ap_const_logic_0;
        end if; 
    end process;

    p_cast_fu_583_p4 <= add2_i_fu_577_p2(13 downto 4);
    shl_i_fu_613_p3 <= (rampStart & ap_const_lv8_0);
    sub10_i_fu_647_p2 <= std_logic_vector(unsigned(height_val_cast15_fu_599_p1) + unsigned(ap_const_lv17_1FFFF));
    sub35_i_fu_641_p2 <= std_logic_vector(unsigned(width_val_cast14_fu_549_p1) + unsigned(ap_const_lv17_1FFFF));
    sub_i_i_i_fu_635_p2 <= std_logic_vector(unsigned(barHeight_cast_fu_631_p1) + unsigned(ap_const_lv11_7FF));
    tmp_3_fu_621_p4 <= add5_i_fu_607_p2(13 downto 4);
    trunc_ln563_fu_810_p1 <= y_fu_214(8 - 1 downto 0);

    width_val12_c24_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val12_c24_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val12_c24_blk_n <= width_val12_c24_full_n;
        else 
            width_val12_c24_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val12_c24_din <= width_val;

    width_val12_c24_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val12_c24_write <= ap_const_logic_1;
        else 
            width_val12_c24_write <= ap_const_logic_0;
        end if; 
    end process;

    width_val_cast14_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_val),17));
    zext_ln1257_fu_667_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rampVal),16));
    zext_ln1412_fu_683_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel),8));
    zext_ln1545_fu_691_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_0),8));
    zext_ln1664_fu_707_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_3_0),8));
    zext_ln1775_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(vBarSel_1),8));
    zext_ln563_1_fu_814_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_214),17));
    zext_ln563_fu_727_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(hBarSel_5_0),8));
end behav;
