set_property SRC_FILE_INFO {cfile:C:/va/z702/axi4_ddr/project_1/project_1.srcs/constrs_1/new/ddr.xdc rfile:../../../project_1.srcs/constrs_1/new/ddr.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E15 [get_ports compare_done]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D15 [get_ports error_flag]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F19 [get_ports key_in]
