// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_v_tpgHlsDataFlow (
        height_val7,
        width_val12,
        field_id_val13,
        fid_in_val14,
        bckgndId_val15,
        ovrlayId_val16,
        maskId_val17,
        motionSpeed_val19,
        colorFormat_val,
        crossHairX_val22,
        crossHairY_val23,
        ZplateHorContStart_val24,
        ZplateHorContDelta_val25,
        ZplateVerContStart_val26,
        ZplateVerContDelta_val27,
        boxSize_val28,
        boxColorR_val29,
        boxColorG_val30,
        boxColorB_val31,
        dpYUVCoef_val32,
        m_axis_video_TDATA,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        fid,
        s,
        ap_clk,
        ap_rst,
        field_id_val13_ap_vld,
        fid_in_val14_ap_vld,
        ovrlayId_val16_ap_vld,
        maskId_val17_ap_vld,
        colorFormat_val_ap_vld,
        crossHairX_val22_ap_vld,
        crossHairY_val23_ap_vld,
        boxSize_val28_ap_vld,
        boxColorR_val29_ap_vld,
        boxColorG_val30_ap_vld,
        boxColorB_val31_ap_vld,
        ap_start,
        height_val7_ap_vld,
        width_val12_ap_vld,
        bckgndId_val15_ap_vld,
        ZplateHorContStart_val24_ap_vld,
        ZplateHorContDelta_val25_ap_vld,
        ZplateVerContStart_val26_ap_vld,
        ZplateVerContDelta_val27_ap_vld,
        dpYUVCoef_val32_ap_vld,
        motionSpeed_val19_ap_vld,
        s_ap_vld,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        fid_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [15:0] height_val7;
input  [15:0] width_val12;
input  [15:0] field_id_val13;
input  [0:0] fid_in_val14;
input  [7:0] bckgndId_val15;
input  [7:0] ovrlayId_val16;
input  [7:0] maskId_val17;
input  [7:0] motionSpeed_val19;
input  [7:0] colorFormat_val;
input  [15:0] crossHairX_val22;
input  [15:0] crossHairY_val23;
input  [15:0] ZplateHorContStart_val24;
input  [15:0] ZplateHorContDelta_val25;
input  [15:0] ZplateVerContStart_val26;
input  [15:0] ZplateVerContDelta_val27;
input  [15:0] boxSize_val28;
input  [7:0] boxColorR_val29;
input  [7:0] boxColorG_val30;
input  [7:0] boxColorB_val31;
input  [7:0] dpYUVCoef_val32;
output  [23:0] m_axis_video_TDATA;
output  [2:0] m_axis_video_TKEEP;
output  [2:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
output  [0:0] fid;
input  [31:0] s;
input   ap_clk;
input   ap_rst;
input   field_id_val13_ap_vld;
input   fid_in_val14_ap_vld;
input   ovrlayId_val16_ap_vld;
input   maskId_val17_ap_vld;
input   colorFormat_val_ap_vld;
input   crossHairX_val22_ap_vld;
input   crossHairY_val23_ap_vld;
input   boxSize_val28_ap_vld;
input   boxColorR_val29_ap_vld;
input   boxColorG_val30_ap_vld;
input   boxColorB_val31_ap_vld;
input   ap_start;
input   height_val7_ap_vld;
input   width_val12_ap_vld;
input   bckgndId_val15_ap_vld;
input   ZplateHorContStart_val24_ap_vld;
input   ZplateHorContDelta_val25_ap_vld;
input   ZplateVerContStart_val26_ap_vld;
input   ZplateVerContDelta_val27_ap_vld;
input   dpYUVCoef_val32_ap_vld;
input   motionSpeed_val19_ap_vld;
input   s_ap_vld;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output   fid_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_start_full_n;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [15:0] entry_proc_U0_field_id_val13_c_din;
wire    entry_proc_U0_field_id_val13_c_write;
wire   [0:0] entry_proc_U0_fid_in_val14_c_din;
wire    entry_proc_U0_fid_in_val14_c_write;
wire   [7:0] entry_proc_U0_ovrlayId_val16_c_din;
wire    entry_proc_U0_ovrlayId_val16_c_write;
wire   [7:0] entry_proc_U0_maskId_val17_c_din;
wire    entry_proc_U0_maskId_val17_c_write;
wire   [7:0] entry_proc_U0_colorFormat_val_c25_din;
wire    entry_proc_U0_colorFormat_val_c25_write;
wire   [15:0] entry_proc_U0_crossHairX_val22_c_din;
wire    entry_proc_U0_crossHairX_val22_c_write;
wire   [15:0] entry_proc_U0_crossHairY_val23_c_din;
wire    entry_proc_U0_crossHairY_val23_c_write;
wire   [15:0] entry_proc_U0_boxSize_val28_c_din;
wire    entry_proc_U0_boxSize_val28_c_write;
wire   [7:0] entry_proc_U0_boxColorR_val29_c_din;
wire    entry_proc_U0_boxColorR_val29_c_write;
wire   [7:0] entry_proc_U0_boxColorG_val30_c_din;
wire    entry_proc_U0_boxColorG_val30_c_write;
wire   [7:0] entry_proc_U0_boxColorB_val31_c_din;
wire    entry_proc_U0_boxColorB_val31_c_write;
wire    tpgBackground_U0_ap_start;
wire    tpgBackground_U0_ap_done;
wire    tpgBackground_U0_ap_continue;
wire    tpgBackground_U0_ap_idle;
wire    tpgBackground_U0_ap_ready;
wire   [23:0] tpgBackground_U0_bckgndYUV_din;
wire    tpgBackground_U0_bckgndYUV_write;
wire   [15:0] tpgBackground_U0_height_val7_c21_din;
wire    tpgBackground_U0_height_val7_c21_write;
wire   [15:0] tpgBackground_U0_width_val12_c24_din;
wire    tpgBackground_U0_width_val12_c24_write;
wire   [7:0] tpgBackground_U0_motionSpeed_val19_c_din;
wire    tpgBackground_U0_motionSpeed_val19_c_write;
wire    tpgForeground_U0_ap_start;
wire    tpgForeground_U0_ap_done;
wire    tpgForeground_U0_ap_continue;
wire    tpgForeground_U0_ap_idle;
wire    tpgForeground_U0_ap_ready;
wire    tpgForeground_U0_bckgndYUV_read;
wire    tpgForeground_U0_height_val_read;
wire    tpgForeground_U0_width_val_read;
wire    tpgForeground_U0_patternId_val_read;
wire    tpgForeground_U0_maskId_val_read;
wire    tpgForeground_U0_colorFormat_val_read;
wire    tpgForeground_U0_crossHairX_val_read;
wire    tpgForeground_U0_crossHairY_val_read;
wire    tpgForeground_U0_boxSize_val_read;
wire    tpgForeground_U0_boxColorR_val_read;
wire    tpgForeground_U0_boxColorG_val_read;
wire    tpgForeground_U0_boxColorB_val_read;
wire    tpgForeground_U0_motionSpeed_val_read;
wire   [23:0] tpgForeground_U0_ovrlayYUV_din;
wire    tpgForeground_U0_ovrlayYUV_write;
wire   [15:0] tpgForeground_U0_height_val7_c20_din;
wire    tpgForeground_U0_height_val7_c20_write;
wire   [15:0] tpgForeground_U0_width_val12_c23_din;
wire    tpgForeground_U0_width_val12_c23_write;
wire   [7:0] tpgForeground_U0_colorFormat_val_c_din;
wire    tpgForeground_U0_colorFormat_val_c_write;
wire    v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_start;
wire    v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_done;
wire    v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_continue;
wire    v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_idle;
wire    v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready;
wire   [0:0] v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_return_0;
wire   [0:0] v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_return_1;
wire    ap_channel_done_bPassThru_loc_channel;
wire    bPassThru_loc_channel_full_n;
reg    ap_sync_reg_channel_write_bPassThru_loc_channel;
wire    ap_sync_channel_write_bPassThru_loc_channel;
wire    ap_channel_done_icmp_ln377_1_loc_channel;
wire    icmp_ln377_1_loc_channel_full_n;
reg    ap_sync_reg_channel_write_icmp_ln377_1_loc_channel;
wire    ap_sync_channel_write_icmp_ln377_1_loc_channel;
wire    v_hcresampler_core_U0_ap_start;
wire    v_hcresampler_core_U0_ap_done;
wire    v_hcresampler_core_U0_ap_continue;
wire    v_hcresampler_core_U0_ap_idle;
wire    v_hcresampler_core_U0_ap_ready;
wire    v_hcresampler_core_U0_ovrlayYUV_read;
wire    v_hcresampler_core_U0_height_val7_read;
wire    v_hcresampler_core_U0_width_val12_read;
wire   [23:0] v_hcresampler_core_U0_stream_out_hresampled_din;
wire    v_hcresampler_core_U0_stream_out_hresampled_write;
wire   [15:0] v_hcresampler_core_U0_height_val7_c19_din;
wire    v_hcresampler_core_U0_height_val7_c19_write;
wire   [15:0] v_hcresampler_core_U0_width_val12_c22_din;
wire    v_hcresampler_core_U0_width_val12_c22_write;
wire    v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_start;
wire    v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_done;
wire    v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_continue;
wire    v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_idle;
wire    v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_ready;
wire   [0:0] v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_return;
wire    bPassThru_1_loc_channel_full_n;
wire    v_vcresampler_core_U0_ap_start;
wire    v_vcresampler_core_U0_ap_done;
wire    v_vcresampler_core_U0_ap_continue;
wire    v_vcresampler_core_U0_ap_idle;
wire    v_vcresampler_core_U0_ap_ready;
wire    v_vcresampler_core_U0_stream_out_hresampled_read;
wire    v_vcresampler_core_U0_height_val7_read;
wire    v_vcresampler_core_U0_width_val12_read;
wire   [23:0] v_vcresampler_core_U0_stream_out_vresampled_din;
wire    v_vcresampler_core_U0_stream_out_vresampled_write;
wire   [11:0] v_vcresampler_core_U0_height_val7_c_din;
wire    v_vcresampler_core_U0_height_val7_c_write;
wire   [12:0] v_vcresampler_core_U0_width_val12_c_din;
wire    v_vcresampler_core_U0_width_val12_c_write;
wire    MultiPixStream2AXIvideo_U0_ap_start;
wire    MultiPixStream2AXIvideo_U0_ap_done;
wire    MultiPixStream2AXIvideo_U0_ap_continue;
wire    MultiPixStream2AXIvideo_U0_ap_idle;
wire    MultiPixStream2AXIvideo_U0_ap_ready;
wire    MultiPixStream2AXIvideo_U0_stream_out_vresampled_read;
wire   [23:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;
wire    MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;
wire   [2:0] MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TID;
wire   [0:0] MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;
wire    MultiPixStream2AXIvideo_U0_height_val7_read;
wire    MultiPixStream2AXIvideo_U0_width_val12_read;
wire    MultiPixStream2AXIvideo_U0_colorFormat_val_read;
wire    MultiPixStream2AXIvideo_U0_fid_in_val14_read;
wire   [0:0] MultiPixStream2AXIvideo_U0_fid;
wire    MultiPixStream2AXIvideo_U0_fid_ap_vld;
wire    MultiPixStream2AXIvideo_U0_field_id_val13_read;
wire    field_id_val13_c_full_n;
wire   [15:0] field_id_val13_c_dout;
wire   [3:0] field_id_val13_c_num_data_valid;
wire   [3:0] field_id_val13_c_fifo_cap;
wire    field_id_val13_c_empty_n;
wire    fid_in_val14_c_full_n;
wire   [0:0] fid_in_val14_c_dout;
wire   [3:0] fid_in_val14_c_num_data_valid;
wire   [3:0] fid_in_val14_c_fifo_cap;
wire    fid_in_val14_c_empty_n;
wire    ovrlayId_val16_c_full_n;
wire   [7:0] ovrlayId_val16_c_dout;
wire   [2:0] ovrlayId_val16_c_num_data_valid;
wire   [2:0] ovrlayId_val16_c_fifo_cap;
wire    ovrlayId_val16_c_empty_n;
wire    maskId_val17_c_full_n;
wire   [7:0] maskId_val17_c_dout;
wire   [2:0] maskId_val17_c_num_data_valid;
wire   [2:0] maskId_val17_c_fifo_cap;
wire    maskId_val17_c_empty_n;
wire    colorFormat_val_c25_full_n;
wire   [7:0] colorFormat_val_c25_dout;
wire   [2:0] colorFormat_val_c25_num_data_valid;
wire   [2:0] colorFormat_val_c25_fifo_cap;
wire    colorFormat_val_c25_empty_n;
wire    crossHairX_val22_c_full_n;
wire   [15:0] crossHairX_val22_c_dout;
wire   [2:0] crossHairX_val22_c_num_data_valid;
wire   [2:0] crossHairX_val22_c_fifo_cap;
wire    crossHairX_val22_c_empty_n;
wire    crossHairY_val23_c_full_n;
wire   [15:0] crossHairY_val23_c_dout;
wire   [2:0] crossHairY_val23_c_num_data_valid;
wire   [2:0] crossHairY_val23_c_fifo_cap;
wire    crossHairY_val23_c_empty_n;
wire    boxSize_val28_c_full_n;
wire   [15:0] boxSize_val28_c_dout;
wire   [2:0] boxSize_val28_c_num_data_valid;
wire   [2:0] boxSize_val28_c_fifo_cap;
wire    boxSize_val28_c_empty_n;
wire    boxColorR_val29_c_full_n;
wire   [7:0] boxColorR_val29_c_dout;
wire   [2:0] boxColorR_val29_c_num_data_valid;
wire   [2:0] boxColorR_val29_c_fifo_cap;
wire    boxColorR_val29_c_empty_n;
wire    boxColorG_val30_c_full_n;
wire   [7:0] boxColorG_val30_c_dout;
wire   [2:0] boxColorG_val30_c_num_data_valid;
wire   [2:0] boxColorG_val30_c_fifo_cap;
wire    boxColorG_val30_c_empty_n;
wire    boxColorB_val31_c_full_n;
wire   [7:0] boxColorB_val31_c_dout;
wire   [2:0] boxColorB_val31_c_num_data_valid;
wire   [2:0] boxColorB_val31_c_fifo_cap;
wire    boxColorB_val31_c_empty_n;
wire    bckgndYUV_full_n;
wire   [23:0] bckgndYUV_dout;
wire   [4:0] bckgndYUV_num_data_valid;
wire   [4:0] bckgndYUV_fifo_cap;
wire    bckgndYUV_empty_n;
wire    height_val7_c21_full_n;
wire   [15:0] height_val7_c21_dout;
wire   [2:0] height_val7_c21_num_data_valid;
wire   [2:0] height_val7_c21_fifo_cap;
wire    height_val7_c21_empty_n;
wire    width_val12_c24_full_n;
wire   [15:0] width_val12_c24_dout;
wire   [2:0] width_val12_c24_num_data_valid;
wire   [2:0] width_val12_c24_fifo_cap;
wire    width_val12_c24_empty_n;
wire    motionSpeed_val19_c_full_n;
wire   [7:0] motionSpeed_val19_c_dout;
wire   [2:0] motionSpeed_val19_c_num_data_valid;
wire   [2:0] motionSpeed_val19_c_fifo_cap;
wire    motionSpeed_val19_c_empty_n;
wire    ovrlayYUV_full_n;
wire   [23:0] ovrlayYUV_dout;
wire   [4:0] ovrlayYUV_num_data_valid;
wire   [4:0] ovrlayYUV_fifo_cap;
wire    ovrlayYUV_empty_n;
wire    height_val7_c20_full_n;
wire   [15:0] height_val7_c20_dout;
wire   [2:0] height_val7_c20_num_data_valid;
wire   [2:0] height_val7_c20_fifo_cap;
wire    height_val7_c20_empty_n;
wire    width_val12_c23_full_n;
wire   [15:0] width_val12_c23_dout;
wire   [2:0] width_val12_c23_num_data_valid;
wire   [2:0] width_val12_c23_fifo_cap;
wire    width_val12_c23_empty_n;
wire    colorFormat_val_c_full_n;
wire   [7:0] colorFormat_val_c_dout;
wire   [2:0] colorFormat_val_c_num_data_valid;
wire   [2:0] colorFormat_val_c_fifo_cap;
wire    colorFormat_val_c_empty_n;
wire   [0:0] icmp_ln377_1_loc_channel_dout;
wire   [2:0] icmp_ln377_1_loc_channel_num_data_valid;
wire   [2:0] icmp_ln377_1_loc_channel_fifo_cap;
wire    icmp_ln377_1_loc_channel_empty_n;
wire   [0:0] bPassThru_loc_channel_dout;
wire   [2:0] bPassThru_loc_channel_num_data_valid;
wire   [2:0] bPassThru_loc_channel_fifo_cap;
wire    bPassThru_loc_channel_empty_n;
wire    stream_out_hresampled_full_n;
wire   [23:0] stream_out_hresampled_dout;
wire   [2:0] stream_out_hresampled_num_data_valid;
wire   [2:0] stream_out_hresampled_fifo_cap;
wire    stream_out_hresampled_empty_n;
wire    height_val7_c19_full_n;
wire   [15:0] height_val7_c19_dout;
wire   [2:0] height_val7_c19_num_data_valid;
wire   [2:0] height_val7_c19_fifo_cap;
wire    height_val7_c19_empty_n;
wire    width_val12_c22_full_n;
wire   [15:0] width_val12_c22_dout;
wire   [2:0] width_val12_c22_num_data_valid;
wire   [2:0] width_val12_c22_fifo_cap;
wire    width_val12_c22_empty_n;
wire   [0:0] bPassThru_1_loc_channel_dout;
wire   [2:0] bPassThru_1_loc_channel_num_data_valid;
wire   [2:0] bPassThru_1_loc_channel_fifo_cap;
wire    bPassThru_1_loc_channel_empty_n;
wire    stream_out_vresampled_full_n;
wire   [23:0] stream_out_vresampled_dout;
wire   [2:0] stream_out_vresampled_num_data_valid;
wire   [2:0] stream_out_vresampled_fifo_cap;
wire    stream_out_vresampled_empty_n;
wire    height_val7_c_full_n;
wire   [11:0] height_val7_c_dout;
wire   [2:0] height_val7_c_num_data_valid;
wire   [2:0] height_val7_c_fifo_cap;
wire    height_val7_c_empty_n;
wire    width_val12_c_full_n;
wire   [12:0] width_val12_c_dout;
wire   [2:0] width_val12_c_num_data_valid;
wire   [2:0] width_val12_c_fifo_cap;
wire    width_val12_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_tpgBackground_U0_ap_ready;
wire    ap_sync_tpgBackground_U0_ap_ready;
reg    ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready;
wire    ap_sync_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready;
wire   [0:0] start_for_tpgForeground_U0_din;
wire    start_for_tpgForeground_U0_full_n;
wire   [0:0] start_for_tpgForeground_U0_dout;
wire    start_for_tpgForeground_U0_empty_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_din;
wire    start_for_MultiPixStream2AXIvideo_U0_full_n;
wire   [0:0] start_for_MultiPixStream2AXIvideo_U0_dout;
wire    start_for_MultiPixStream2AXIvideo_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_bPassThru_loc_channel = 1'b0;
#0 ap_sync_reg_channel_write_icmp_ln377_1_loc_channel = 1'b0;
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_tpgBackground_U0_ap_ready = 1'b0;
#0 ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready = 1'b0;
end

design_1_v_tpg_0_0_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(entry_proc_U0_start_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .field_id_val13(field_id_val13),
    .field_id_val13_c_din(entry_proc_U0_field_id_val13_c_din),
    .field_id_val13_c_num_data_valid(field_id_val13_c_num_data_valid),
    .field_id_val13_c_fifo_cap(field_id_val13_c_fifo_cap),
    .field_id_val13_c_full_n(field_id_val13_c_full_n),
    .field_id_val13_c_write(entry_proc_U0_field_id_val13_c_write),
    .fid_in_val14(fid_in_val14),
    .fid_in_val14_c_din(entry_proc_U0_fid_in_val14_c_din),
    .fid_in_val14_c_num_data_valid(fid_in_val14_c_num_data_valid),
    .fid_in_val14_c_fifo_cap(fid_in_val14_c_fifo_cap),
    .fid_in_val14_c_full_n(fid_in_val14_c_full_n),
    .fid_in_val14_c_write(entry_proc_U0_fid_in_val14_c_write),
    .ovrlayId_val16(ovrlayId_val16),
    .ovrlayId_val16_c_din(entry_proc_U0_ovrlayId_val16_c_din),
    .ovrlayId_val16_c_num_data_valid(ovrlayId_val16_c_num_data_valid),
    .ovrlayId_val16_c_fifo_cap(ovrlayId_val16_c_fifo_cap),
    .ovrlayId_val16_c_full_n(ovrlayId_val16_c_full_n),
    .ovrlayId_val16_c_write(entry_proc_U0_ovrlayId_val16_c_write),
    .maskId_val17(maskId_val17),
    .maskId_val17_c_din(entry_proc_U0_maskId_val17_c_din),
    .maskId_val17_c_num_data_valid(maskId_val17_c_num_data_valid),
    .maskId_val17_c_fifo_cap(maskId_val17_c_fifo_cap),
    .maskId_val17_c_full_n(maskId_val17_c_full_n),
    .maskId_val17_c_write(entry_proc_U0_maskId_val17_c_write),
    .colorFormat_val(colorFormat_val),
    .colorFormat_val_c25_din(entry_proc_U0_colorFormat_val_c25_din),
    .colorFormat_val_c25_num_data_valid(colorFormat_val_c25_num_data_valid),
    .colorFormat_val_c25_fifo_cap(colorFormat_val_c25_fifo_cap),
    .colorFormat_val_c25_full_n(colorFormat_val_c25_full_n),
    .colorFormat_val_c25_write(entry_proc_U0_colorFormat_val_c25_write),
    .crossHairX_val22(crossHairX_val22),
    .crossHairX_val22_c_din(entry_proc_U0_crossHairX_val22_c_din),
    .crossHairX_val22_c_num_data_valid(crossHairX_val22_c_num_data_valid),
    .crossHairX_val22_c_fifo_cap(crossHairX_val22_c_fifo_cap),
    .crossHairX_val22_c_full_n(crossHairX_val22_c_full_n),
    .crossHairX_val22_c_write(entry_proc_U0_crossHairX_val22_c_write),
    .crossHairY_val23(crossHairY_val23),
    .crossHairY_val23_c_din(entry_proc_U0_crossHairY_val23_c_din),
    .crossHairY_val23_c_num_data_valid(crossHairY_val23_c_num_data_valid),
    .crossHairY_val23_c_fifo_cap(crossHairY_val23_c_fifo_cap),
    .crossHairY_val23_c_full_n(crossHairY_val23_c_full_n),
    .crossHairY_val23_c_write(entry_proc_U0_crossHairY_val23_c_write),
    .boxSize_val28(boxSize_val28),
    .boxSize_val28_c_din(entry_proc_U0_boxSize_val28_c_din),
    .boxSize_val28_c_num_data_valid(boxSize_val28_c_num_data_valid),
    .boxSize_val28_c_fifo_cap(boxSize_val28_c_fifo_cap),
    .boxSize_val28_c_full_n(boxSize_val28_c_full_n),
    .boxSize_val28_c_write(entry_proc_U0_boxSize_val28_c_write),
    .boxColorR_val29(boxColorR_val29),
    .boxColorR_val29_c_din(entry_proc_U0_boxColorR_val29_c_din),
    .boxColorR_val29_c_num_data_valid(boxColorR_val29_c_num_data_valid),
    .boxColorR_val29_c_fifo_cap(boxColorR_val29_c_fifo_cap),
    .boxColorR_val29_c_full_n(boxColorR_val29_c_full_n),
    .boxColorR_val29_c_write(entry_proc_U0_boxColorR_val29_c_write),
    .boxColorG_val30(boxColorG_val30),
    .boxColorG_val30_c_din(entry_proc_U0_boxColorG_val30_c_din),
    .boxColorG_val30_c_num_data_valid(boxColorG_val30_c_num_data_valid),
    .boxColorG_val30_c_fifo_cap(boxColorG_val30_c_fifo_cap),
    .boxColorG_val30_c_full_n(boxColorG_val30_c_full_n),
    .boxColorG_val30_c_write(entry_proc_U0_boxColorG_val30_c_write),
    .boxColorB_val31(boxColorB_val31),
    .boxColorB_val31_c_din(entry_proc_U0_boxColorB_val31_c_din),
    .boxColorB_val31_c_num_data_valid(boxColorB_val31_c_num_data_valid),
    .boxColorB_val31_c_fifo_cap(boxColorB_val31_c_fifo_cap),
    .boxColorB_val31_c_full_n(boxColorB_val31_c_full_n),
    .boxColorB_val31_c_write(entry_proc_U0_boxColorB_val31_c_write)
);

design_1_v_tpg_0_0_tpgBackground tpgBackground_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(tpgBackground_U0_ap_start),
    .ap_done(tpgBackground_U0_ap_done),
    .ap_continue(tpgBackground_U0_ap_continue),
    .ap_idle(tpgBackground_U0_ap_idle),
    .ap_ready(tpgBackground_U0_ap_ready),
    .height_val(height_val7),
    .width_val(width_val12),
    .patternId_val(bckgndId_val15),
    .ZplateHorContStart_val(ZplateHorContStart_val24),
    .ZplateHorContDelta_val(ZplateHorContDelta_val25),
    .ZplateVerContStart_val(ZplateVerContStart_val26),
    .ZplateVerContDelta_val(ZplateVerContDelta_val27),
    .dpYUVCoef_val(dpYUVCoef_val32),
    .motionSpeed_val(motionSpeed_val19),
    .bckgndYUV_din(tpgBackground_U0_bckgndYUV_din),
    .bckgndYUV_num_data_valid(bckgndYUV_num_data_valid),
    .bckgndYUV_fifo_cap(bckgndYUV_fifo_cap),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(tpgBackground_U0_bckgndYUV_write),
    .height_val7_c21_din(tpgBackground_U0_height_val7_c21_din),
    .height_val7_c21_num_data_valid(height_val7_c21_num_data_valid),
    .height_val7_c21_fifo_cap(height_val7_c21_fifo_cap),
    .height_val7_c21_full_n(height_val7_c21_full_n),
    .height_val7_c21_write(tpgBackground_U0_height_val7_c21_write),
    .width_val12_c24_din(tpgBackground_U0_width_val12_c24_din),
    .width_val12_c24_num_data_valid(width_val12_c24_num_data_valid),
    .width_val12_c24_fifo_cap(width_val12_c24_fifo_cap),
    .width_val12_c24_full_n(width_val12_c24_full_n),
    .width_val12_c24_write(tpgBackground_U0_width_val12_c24_write),
    .motionSpeed_val19_c_din(tpgBackground_U0_motionSpeed_val19_c_din),
    .motionSpeed_val19_c_num_data_valid(motionSpeed_val19_c_num_data_valid),
    .motionSpeed_val19_c_fifo_cap(motionSpeed_val19_c_fifo_cap),
    .motionSpeed_val19_c_full_n(motionSpeed_val19_c_full_n),
    .motionSpeed_val19_c_write(tpgBackground_U0_motionSpeed_val19_c_write),
    .s(s)
);

design_1_v_tpg_0_0_tpgForeground tpgForeground_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(tpgForeground_U0_ap_start),
    .ap_done(tpgForeground_U0_ap_done),
    .ap_continue(tpgForeground_U0_ap_continue),
    .ap_idle(tpgForeground_U0_ap_idle),
    .ap_ready(tpgForeground_U0_ap_ready),
    .bckgndYUV_dout(bckgndYUV_dout),
    .bckgndYUV_num_data_valid(bckgndYUV_num_data_valid),
    .bckgndYUV_fifo_cap(bckgndYUV_fifo_cap),
    .bckgndYUV_empty_n(bckgndYUV_empty_n),
    .bckgndYUV_read(tpgForeground_U0_bckgndYUV_read),
    .height_val_dout(height_val7_c21_dout),
    .height_val_num_data_valid(height_val7_c21_num_data_valid),
    .height_val_fifo_cap(height_val7_c21_fifo_cap),
    .height_val_empty_n(height_val7_c21_empty_n),
    .height_val_read(tpgForeground_U0_height_val_read),
    .width_val_dout(width_val12_c24_dout),
    .width_val_num_data_valid(width_val12_c24_num_data_valid),
    .width_val_fifo_cap(width_val12_c24_fifo_cap),
    .width_val_empty_n(width_val12_c24_empty_n),
    .width_val_read(tpgForeground_U0_width_val_read),
    .patternId_val_dout(ovrlayId_val16_c_dout),
    .patternId_val_num_data_valid(ovrlayId_val16_c_num_data_valid),
    .patternId_val_fifo_cap(ovrlayId_val16_c_fifo_cap),
    .patternId_val_empty_n(ovrlayId_val16_c_empty_n),
    .patternId_val_read(tpgForeground_U0_patternId_val_read),
    .maskId_val_dout(maskId_val17_c_dout),
    .maskId_val_num_data_valid(maskId_val17_c_num_data_valid),
    .maskId_val_fifo_cap(maskId_val17_c_fifo_cap),
    .maskId_val_empty_n(maskId_val17_c_empty_n),
    .maskId_val_read(tpgForeground_U0_maskId_val_read),
    .colorFormat_val_dout(colorFormat_val_c25_dout),
    .colorFormat_val_num_data_valid(colorFormat_val_c25_num_data_valid),
    .colorFormat_val_fifo_cap(colorFormat_val_c25_fifo_cap),
    .colorFormat_val_empty_n(colorFormat_val_c25_empty_n),
    .colorFormat_val_read(tpgForeground_U0_colorFormat_val_read),
    .crossHairX_val_dout(crossHairX_val22_c_dout),
    .crossHairX_val_num_data_valid(crossHairX_val22_c_num_data_valid),
    .crossHairX_val_fifo_cap(crossHairX_val22_c_fifo_cap),
    .crossHairX_val_empty_n(crossHairX_val22_c_empty_n),
    .crossHairX_val_read(tpgForeground_U0_crossHairX_val_read),
    .crossHairY_val_dout(crossHairY_val23_c_dout),
    .crossHairY_val_num_data_valid(crossHairY_val23_c_num_data_valid),
    .crossHairY_val_fifo_cap(crossHairY_val23_c_fifo_cap),
    .crossHairY_val_empty_n(crossHairY_val23_c_empty_n),
    .crossHairY_val_read(tpgForeground_U0_crossHairY_val_read),
    .boxSize_val_dout(boxSize_val28_c_dout),
    .boxSize_val_num_data_valid(boxSize_val28_c_num_data_valid),
    .boxSize_val_fifo_cap(boxSize_val28_c_fifo_cap),
    .boxSize_val_empty_n(boxSize_val28_c_empty_n),
    .boxSize_val_read(tpgForeground_U0_boxSize_val_read),
    .boxColorR_val_dout(boxColorR_val29_c_dout),
    .boxColorR_val_num_data_valid(boxColorR_val29_c_num_data_valid),
    .boxColorR_val_fifo_cap(boxColorR_val29_c_fifo_cap),
    .boxColorR_val_empty_n(boxColorR_val29_c_empty_n),
    .boxColorR_val_read(tpgForeground_U0_boxColorR_val_read),
    .boxColorG_val_dout(boxColorG_val30_c_dout),
    .boxColorG_val_num_data_valid(boxColorG_val30_c_num_data_valid),
    .boxColorG_val_fifo_cap(boxColorG_val30_c_fifo_cap),
    .boxColorG_val_empty_n(boxColorG_val30_c_empty_n),
    .boxColorG_val_read(tpgForeground_U0_boxColorG_val_read),
    .boxColorB_val_dout(boxColorB_val31_c_dout),
    .boxColorB_val_num_data_valid(boxColorB_val31_c_num_data_valid),
    .boxColorB_val_fifo_cap(boxColorB_val31_c_fifo_cap),
    .boxColorB_val_empty_n(boxColorB_val31_c_empty_n),
    .boxColorB_val_read(tpgForeground_U0_boxColorB_val_read),
    .motionSpeed_val_dout(motionSpeed_val19_c_dout),
    .motionSpeed_val_num_data_valid(motionSpeed_val19_c_num_data_valid),
    .motionSpeed_val_fifo_cap(motionSpeed_val19_c_fifo_cap),
    .motionSpeed_val_empty_n(motionSpeed_val19_c_empty_n),
    .motionSpeed_val_read(tpgForeground_U0_motionSpeed_val_read),
    .ovrlayYUV_din(tpgForeground_U0_ovrlayYUV_din),
    .ovrlayYUV_num_data_valid(ovrlayYUV_num_data_valid),
    .ovrlayYUV_fifo_cap(ovrlayYUV_fifo_cap),
    .ovrlayYUV_full_n(ovrlayYUV_full_n),
    .ovrlayYUV_write(tpgForeground_U0_ovrlayYUV_write),
    .height_val7_c20_din(tpgForeground_U0_height_val7_c20_din),
    .height_val7_c20_num_data_valid(height_val7_c20_num_data_valid),
    .height_val7_c20_fifo_cap(height_val7_c20_fifo_cap),
    .height_val7_c20_full_n(height_val7_c20_full_n),
    .height_val7_c20_write(tpgForeground_U0_height_val7_c20_write),
    .width_val12_c23_din(tpgForeground_U0_width_val12_c23_din),
    .width_val12_c23_num_data_valid(width_val12_c23_num_data_valid),
    .width_val12_c23_fifo_cap(width_val12_c23_fifo_cap),
    .width_val12_c23_full_n(width_val12_c23_full_n),
    .width_val12_c23_write(tpgForeground_U0_width_val12_c23_write),
    .colorFormat_val_c_din(tpgForeground_U0_colorFormat_val_c_din),
    .colorFormat_val_c_num_data_valid(colorFormat_val_c_num_data_valid),
    .colorFormat_val_c_fifo_cap(colorFormat_val_c_fifo_cap),
    .colorFormat_val_c_full_n(colorFormat_val_c_full_n),
    .colorFormat_val_c_write(tpgForeground_U0_colorFormat_val_c_write)
);

design_1_v_tpg_0_0_v_tpgHlsDataFlow_Block_entry36_proc v_tpgHlsDataFlow_Block_entry36_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_start),
    .ap_done(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_done),
    .ap_continue(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_continue),
    .ap_idle(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_idle),
    .ap_ready(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready),
    .colorFormat_val(colorFormat_val),
    .ap_return_0(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_return_0),
    .ap_return_1(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_return_1)
);

design_1_v_tpg_0_0_v_hcresampler_core v_hcresampler_core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_hcresampler_core_U0_ap_start),
    .ap_done(v_hcresampler_core_U0_ap_done),
    .ap_continue(v_hcresampler_core_U0_ap_continue),
    .ap_idle(v_hcresampler_core_U0_ap_idle),
    .ap_ready(v_hcresampler_core_U0_ap_ready),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_num_data_valid(ovrlayYUV_num_data_valid),
    .ovrlayYUV_fifo_cap(ovrlayYUV_fifo_cap),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(v_hcresampler_core_U0_ovrlayYUV_read),
    .height_val7_dout(height_val7_c20_dout),
    .height_val7_num_data_valid(height_val7_c20_num_data_valid),
    .height_val7_fifo_cap(height_val7_c20_fifo_cap),
    .height_val7_empty_n(height_val7_c20_empty_n),
    .height_val7_read(v_hcresampler_core_U0_height_val7_read),
    .width_val12_dout(width_val12_c23_dout),
    .width_val12_num_data_valid(width_val12_c23_num_data_valid),
    .width_val12_fifo_cap(width_val12_c23_fifo_cap),
    .width_val12_empty_n(width_val12_c23_empty_n),
    .width_val12_read(v_hcresampler_core_U0_width_val12_read),
    .p_read(bPassThru_loc_channel_dout),
    .stream_out_hresampled_din(v_hcresampler_core_U0_stream_out_hresampled_din),
    .stream_out_hresampled_num_data_valid(stream_out_hresampled_num_data_valid),
    .stream_out_hresampled_fifo_cap(stream_out_hresampled_fifo_cap),
    .stream_out_hresampled_full_n(stream_out_hresampled_full_n),
    .stream_out_hresampled_write(v_hcresampler_core_U0_stream_out_hresampled_write),
    .height_val7_c19_din(v_hcresampler_core_U0_height_val7_c19_din),
    .height_val7_c19_num_data_valid(height_val7_c19_num_data_valid),
    .height_val7_c19_fifo_cap(height_val7_c19_fifo_cap),
    .height_val7_c19_full_n(height_val7_c19_full_n),
    .height_val7_c19_write(v_hcresampler_core_U0_height_val7_c19_write),
    .width_val12_c22_din(v_hcresampler_core_U0_width_val12_c22_din),
    .width_val12_c22_num_data_valid(width_val12_c22_num_data_valid),
    .width_val12_c22_fifo_cap(width_val12_c22_fifo_cap),
    .width_val12_c22_full_n(width_val12_c22_full_n),
    .width_val12_c22_write(v_hcresampler_core_U0_width_val12_c22_write)
);

design_1_v_tpg_0_0_v_tpgHlsDataFlow_Block_entry38_proc v_tpgHlsDataFlow_Block_entry38_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_start),
    .ap_done(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_done),
    .ap_continue(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_continue),
    .ap_idle(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_idle),
    .ap_ready(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_ready),
    .p_read(icmp_ln377_1_loc_channel_dout),
    .ap_return(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_return)
);

design_1_v_tpg_0_0_v_vcresampler_core v_vcresampler_core_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(v_vcresampler_core_U0_ap_start),
    .ap_done(v_vcresampler_core_U0_ap_done),
    .ap_continue(v_vcresampler_core_U0_ap_continue),
    .ap_idle(v_vcresampler_core_U0_ap_idle),
    .ap_ready(v_vcresampler_core_U0_ap_ready),
    .stream_out_hresampled_dout(stream_out_hresampled_dout),
    .stream_out_hresampled_num_data_valid(stream_out_hresampled_num_data_valid),
    .stream_out_hresampled_fifo_cap(stream_out_hresampled_fifo_cap),
    .stream_out_hresampled_empty_n(stream_out_hresampled_empty_n),
    .stream_out_hresampled_read(v_vcresampler_core_U0_stream_out_hresampled_read),
    .height_val7_dout(height_val7_c19_dout),
    .height_val7_num_data_valid(height_val7_c19_num_data_valid),
    .height_val7_fifo_cap(height_val7_c19_fifo_cap),
    .height_val7_empty_n(height_val7_c19_empty_n),
    .height_val7_read(v_vcresampler_core_U0_height_val7_read),
    .width_val12_dout(width_val12_c22_dout),
    .width_val12_num_data_valid(width_val12_c22_num_data_valid),
    .width_val12_fifo_cap(width_val12_c22_fifo_cap),
    .width_val12_empty_n(width_val12_c22_empty_n),
    .width_val12_read(v_vcresampler_core_U0_width_val12_read),
    .p_read(bPassThru_1_loc_channel_dout),
    .stream_out_vresampled_din(v_vcresampler_core_U0_stream_out_vresampled_din),
    .stream_out_vresampled_num_data_valid(stream_out_vresampled_num_data_valid),
    .stream_out_vresampled_fifo_cap(stream_out_vresampled_fifo_cap),
    .stream_out_vresampled_full_n(stream_out_vresampled_full_n),
    .stream_out_vresampled_write(v_vcresampler_core_U0_stream_out_vresampled_write),
    .height_val7_c_din(v_vcresampler_core_U0_height_val7_c_din),
    .height_val7_c_num_data_valid(height_val7_c_num_data_valid),
    .height_val7_c_fifo_cap(height_val7_c_fifo_cap),
    .height_val7_c_full_n(height_val7_c_full_n),
    .height_val7_c_write(v_vcresampler_core_U0_height_val7_c_write),
    .width_val12_c_din(v_vcresampler_core_U0_width_val12_c_din),
    .width_val12_c_num_data_valid(width_val12_c_num_data_valid),
    .width_val12_c_fifo_cap(width_val12_c_fifo_cap),
    .width_val12_c_full_n(width_val12_c_full_n),
    .width_val12_c_write(v_vcresampler_core_U0_width_val12_c_write)
);

design_1_v_tpg_0_0_MultiPixStream2AXIvideo MultiPixStream2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MultiPixStream2AXIvideo_U0_ap_start),
    .ap_done(MultiPixStream2AXIvideo_U0_ap_done),
    .ap_continue(MultiPixStream2AXIvideo_U0_ap_continue),
    .ap_idle(MultiPixStream2AXIvideo_U0_ap_idle),
    .ap_ready(MultiPixStream2AXIvideo_U0_ap_ready),
    .stream_out_vresampled_dout(stream_out_vresampled_dout),
    .stream_out_vresampled_num_data_valid(stream_out_vresampled_num_data_valid),
    .stream_out_vresampled_fifo_cap(stream_out_vresampled_fifo_cap),
    .stream_out_vresampled_empty_n(stream_out_vresampled_empty_n),
    .stream_out_vresampled_read(MultiPixStream2AXIvideo_U0_stream_out_vresampled_read),
    .m_axis_video_TDATA(MultiPixStream2AXIvideo_U0_m_axis_video_TDATA),
    .m_axis_video_TVALID(MultiPixStream2AXIvideo_U0_m_axis_video_TVALID),
    .m_axis_video_TREADY(m_axis_video_TREADY),
    .m_axis_video_TKEEP(MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB),
    .m_axis_video_TUSER(MultiPixStream2AXIvideo_U0_m_axis_video_TUSER),
    .m_axis_video_TLAST(MultiPixStream2AXIvideo_U0_m_axis_video_TLAST),
    .m_axis_video_TID(MultiPixStream2AXIvideo_U0_m_axis_video_TID),
    .m_axis_video_TDEST(MultiPixStream2AXIvideo_U0_m_axis_video_TDEST),
    .height_val7_dout(height_val7_c_dout),
    .height_val7_num_data_valid(height_val7_c_num_data_valid),
    .height_val7_fifo_cap(height_val7_c_fifo_cap),
    .height_val7_empty_n(height_val7_c_empty_n),
    .height_val7_read(MultiPixStream2AXIvideo_U0_height_val7_read),
    .width_val12_dout(width_val12_c_dout),
    .width_val12_num_data_valid(width_val12_c_num_data_valid),
    .width_val12_fifo_cap(width_val12_c_fifo_cap),
    .width_val12_empty_n(width_val12_c_empty_n),
    .width_val12_read(MultiPixStream2AXIvideo_U0_width_val12_read),
    .colorFormat_val_dout(colorFormat_val_c_dout),
    .colorFormat_val_num_data_valid(colorFormat_val_c_num_data_valid),
    .colorFormat_val_fifo_cap(colorFormat_val_c_fifo_cap),
    .colorFormat_val_empty_n(colorFormat_val_c_empty_n),
    .colorFormat_val_read(MultiPixStream2AXIvideo_U0_colorFormat_val_read),
    .fid_in_val14_dout(fid_in_val14_c_dout),
    .fid_in_val14_num_data_valid(fid_in_val14_c_num_data_valid),
    .fid_in_val14_fifo_cap(fid_in_val14_c_fifo_cap),
    .fid_in_val14_empty_n(fid_in_val14_c_empty_n),
    .fid_in_val14_read(MultiPixStream2AXIvideo_U0_fid_in_val14_read),
    .fid(MultiPixStream2AXIvideo_U0_fid),
    .fid_ap_vld(MultiPixStream2AXIvideo_U0_fid_ap_vld),
    .field_id_val13_dout(field_id_val13_c_dout),
    .field_id_val13_num_data_valid(field_id_val13_c_num_data_valid),
    .field_id_val13_fifo_cap(field_id_val13_c_fifo_cap),
    .field_id_val13_empty_n(field_id_val13_c_empty_n),
    .field_id_val13_read(MultiPixStream2AXIvideo_U0_field_id_val13_read)
);

design_1_v_tpg_0_0_fifo_w16_d6_S field_id_val13_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_field_id_val13_c_din),
    .if_full_n(field_id_val13_c_full_n),
    .if_write(entry_proc_U0_field_id_val13_c_write),
    .if_dout(field_id_val13_c_dout),
    .if_num_data_valid(field_id_val13_c_num_data_valid),
    .if_fifo_cap(field_id_val13_c_fifo_cap),
    .if_empty_n(field_id_val13_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_field_id_val13_read)
);

design_1_v_tpg_0_0_fifo_w1_d6_S fid_in_val14_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_fid_in_val14_c_din),
    .if_full_n(fid_in_val14_c_full_n),
    .if_write(entry_proc_U0_fid_in_val14_c_write),
    .if_dout(fid_in_val14_c_dout),
    .if_num_data_valid(fid_in_val14_c_num_data_valid),
    .if_fifo_cap(fid_in_val14_c_fifo_cap),
    .if_empty_n(fid_in_val14_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_fid_in_val14_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S ovrlayId_val16_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_ovrlayId_val16_c_din),
    .if_full_n(ovrlayId_val16_c_full_n),
    .if_write(entry_proc_U0_ovrlayId_val16_c_write),
    .if_dout(ovrlayId_val16_c_dout),
    .if_num_data_valid(ovrlayId_val16_c_num_data_valid),
    .if_fifo_cap(ovrlayId_val16_c_fifo_cap),
    .if_empty_n(ovrlayId_val16_c_empty_n),
    .if_read(tpgForeground_U0_patternId_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S maskId_val17_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_maskId_val17_c_din),
    .if_full_n(maskId_val17_c_full_n),
    .if_write(entry_proc_U0_maskId_val17_c_write),
    .if_dout(maskId_val17_c_dout),
    .if_num_data_valid(maskId_val17_c_num_data_valid),
    .if_fifo_cap(maskId_val17_c_fifo_cap),
    .if_empty_n(maskId_val17_c_empty_n),
    .if_read(tpgForeground_U0_maskId_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S colorFormat_val_c25_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_colorFormat_val_c25_din),
    .if_full_n(colorFormat_val_c25_full_n),
    .if_write(entry_proc_U0_colorFormat_val_c25_write),
    .if_dout(colorFormat_val_c25_dout),
    .if_num_data_valid(colorFormat_val_c25_num_data_valid),
    .if_fifo_cap(colorFormat_val_c25_fifo_cap),
    .if_empty_n(colorFormat_val_c25_empty_n),
    .if_read(tpgForeground_U0_colorFormat_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S crossHairX_val22_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_crossHairX_val22_c_din),
    .if_full_n(crossHairX_val22_c_full_n),
    .if_write(entry_proc_U0_crossHairX_val22_c_write),
    .if_dout(crossHairX_val22_c_dout),
    .if_num_data_valid(crossHairX_val22_c_num_data_valid),
    .if_fifo_cap(crossHairX_val22_c_fifo_cap),
    .if_empty_n(crossHairX_val22_c_empty_n),
    .if_read(tpgForeground_U0_crossHairX_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S crossHairY_val23_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_crossHairY_val23_c_din),
    .if_full_n(crossHairY_val23_c_full_n),
    .if_write(entry_proc_U0_crossHairY_val23_c_write),
    .if_dout(crossHairY_val23_c_dout),
    .if_num_data_valid(crossHairY_val23_c_num_data_valid),
    .if_fifo_cap(crossHairY_val23_c_fifo_cap),
    .if_empty_n(crossHairY_val23_c_empty_n),
    .if_read(tpgForeground_U0_crossHairY_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d3_S boxSize_val28_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxSize_val28_c_din),
    .if_full_n(boxSize_val28_c_full_n),
    .if_write(entry_proc_U0_boxSize_val28_c_write),
    .if_dout(boxSize_val28_c_dout),
    .if_num_data_valid(boxSize_val28_c_num_data_valid),
    .if_fifo_cap(boxSize_val28_c_fifo_cap),
    .if_empty_n(boxSize_val28_c_empty_n),
    .if_read(tpgForeground_U0_boxSize_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S boxColorR_val29_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxColorR_val29_c_din),
    .if_full_n(boxColorR_val29_c_full_n),
    .if_write(entry_proc_U0_boxColorR_val29_c_write),
    .if_dout(boxColorR_val29_c_dout),
    .if_num_data_valid(boxColorR_val29_c_num_data_valid),
    .if_fifo_cap(boxColorR_val29_c_fifo_cap),
    .if_empty_n(boxColorR_val29_c_empty_n),
    .if_read(tpgForeground_U0_boxColorR_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S boxColorG_val30_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxColorG_val30_c_din),
    .if_full_n(boxColorG_val30_c_full_n),
    .if_write(entry_proc_U0_boxColorG_val30_c_write),
    .if_dout(boxColorG_val30_c_dout),
    .if_num_data_valid(boxColorG_val30_c_num_data_valid),
    .if_fifo_cap(boxColorG_val30_c_fifo_cap),
    .if_empty_n(boxColorG_val30_c_empty_n),
    .if_read(tpgForeground_U0_boxColorG_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d3_S boxColorB_val31_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_boxColorB_val31_c_din),
    .if_full_n(boxColorB_val31_c_full_n),
    .if_write(entry_proc_U0_boxColorB_val31_c_write),
    .if_dout(boxColorB_val31_c_dout),
    .if_num_data_valid(boxColorB_val31_c_num_data_valid),
    .if_fifo_cap(boxColorB_val31_c_fifo_cap),
    .if_empty_n(boxColorB_val31_c_empty_n),
    .if_read(tpgForeground_U0_boxColorB_val_read)
);

design_1_v_tpg_0_0_fifo_w24_d16_S bckgndYUV_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_bckgndYUV_din),
    .if_full_n(bckgndYUV_full_n),
    .if_write(tpgBackground_U0_bckgndYUV_write),
    .if_dout(bckgndYUV_dout),
    .if_num_data_valid(bckgndYUV_num_data_valid),
    .if_fifo_cap(bckgndYUV_fifo_cap),
    .if_empty_n(bckgndYUV_empty_n),
    .if_read(tpgForeground_U0_bckgndYUV_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S height_val7_c21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_height_val7_c21_din),
    .if_full_n(height_val7_c21_full_n),
    .if_write(tpgBackground_U0_height_val7_c21_write),
    .if_dout(height_val7_c21_dout),
    .if_num_data_valid(height_val7_c21_num_data_valid),
    .if_fifo_cap(height_val7_c21_fifo_cap),
    .if_empty_n(height_val7_c21_empty_n),
    .if_read(tpgForeground_U0_height_val_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S width_val12_c24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_width_val12_c24_din),
    .if_full_n(width_val12_c24_full_n),
    .if_write(tpgBackground_U0_width_val12_c24_write),
    .if_dout(width_val12_c24_dout),
    .if_num_data_valid(width_val12_c24_num_data_valid),
    .if_fifo_cap(width_val12_c24_fifo_cap),
    .if_empty_n(width_val12_c24_empty_n),
    .if_read(tpgForeground_U0_width_val_read)
);

design_1_v_tpg_0_0_fifo_w8_d2_S motionSpeed_val19_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgBackground_U0_motionSpeed_val19_c_din),
    .if_full_n(motionSpeed_val19_c_full_n),
    .if_write(tpgBackground_U0_motionSpeed_val19_c_write),
    .if_dout(motionSpeed_val19_c_dout),
    .if_num_data_valid(motionSpeed_val19_c_num_data_valid),
    .if_fifo_cap(motionSpeed_val19_c_fifo_cap),
    .if_empty_n(motionSpeed_val19_c_empty_n),
    .if_read(tpgForeground_U0_motionSpeed_val_read)
);

design_1_v_tpg_0_0_fifo_w24_d16_S ovrlayYUV_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_ovrlayYUV_din),
    .if_full_n(ovrlayYUV_full_n),
    .if_write(tpgForeground_U0_ovrlayYUV_write),
    .if_dout(ovrlayYUV_dout),
    .if_num_data_valid(ovrlayYUV_num_data_valid),
    .if_fifo_cap(ovrlayYUV_fifo_cap),
    .if_empty_n(ovrlayYUV_empty_n),
    .if_read(v_hcresampler_core_U0_ovrlayYUV_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S height_val7_c20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_height_val7_c20_din),
    .if_full_n(height_val7_c20_full_n),
    .if_write(tpgForeground_U0_height_val7_c20_write),
    .if_dout(height_val7_c20_dout),
    .if_num_data_valid(height_val7_c20_num_data_valid),
    .if_fifo_cap(height_val7_c20_fifo_cap),
    .if_empty_n(height_val7_c20_empty_n),
    .if_read(v_hcresampler_core_U0_height_val7_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S width_val12_c23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_width_val12_c23_din),
    .if_full_n(width_val12_c23_full_n),
    .if_write(tpgForeground_U0_width_val12_c23_write),
    .if_dout(width_val12_c23_dout),
    .if_num_data_valid(width_val12_c23_num_data_valid),
    .if_fifo_cap(width_val12_c23_fifo_cap),
    .if_empty_n(width_val12_c23_empty_n),
    .if_read(v_hcresampler_core_U0_width_val12_read)
);

design_1_v_tpg_0_0_fifo_w8_d4_S colorFormat_val_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tpgForeground_U0_colorFormat_val_c_din),
    .if_full_n(colorFormat_val_c_full_n),
    .if_write(tpgForeground_U0_colorFormat_val_c_write),
    .if_dout(colorFormat_val_c_dout),
    .if_num_data_valid(colorFormat_val_c_num_data_valid),
    .if_fifo_cap(colorFormat_val_c_fifo_cap),
    .if_empty_n(colorFormat_val_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_colorFormat_val_read)
);

design_1_v_tpg_0_0_fifo_w1_d2_S icmp_ln377_1_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_return_0),
    .if_full_n(icmp_ln377_1_loc_channel_full_n),
    .if_write(ap_channel_done_icmp_ln377_1_loc_channel),
    .if_dout(icmp_ln377_1_loc_channel_dout),
    .if_num_data_valid(icmp_ln377_1_loc_channel_num_data_valid),
    .if_fifo_cap(icmp_ln377_1_loc_channel_fifo_cap),
    .if_empty_n(icmp_ln377_1_loc_channel_empty_n),
    .if_read(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_ready)
);

design_1_v_tpg_0_0_fifo_w1_d3_S bPassThru_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_return_1),
    .if_full_n(bPassThru_loc_channel_full_n),
    .if_write(ap_channel_done_bPassThru_loc_channel),
    .if_dout(bPassThru_loc_channel_dout),
    .if_num_data_valid(bPassThru_loc_channel_num_data_valid),
    .if_fifo_cap(bPassThru_loc_channel_fifo_cap),
    .if_empty_n(bPassThru_loc_channel_empty_n),
    .if_read(v_hcresampler_core_U0_ap_ready)
);

design_1_v_tpg_0_0_fifo_w24_d2_S stream_out_hresampled_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_hcresampler_core_U0_stream_out_hresampled_din),
    .if_full_n(stream_out_hresampled_full_n),
    .if_write(v_hcresampler_core_U0_stream_out_hresampled_write),
    .if_dout(stream_out_hresampled_dout),
    .if_num_data_valid(stream_out_hresampled_num_data_valid),
    .if_fifo_cap(stream_out_hresampled_fifo_cap),
    .if_empty_n(stream_out_hresampled_empty_n),
    .if_read(v_vcresampler_core_U0_stream_out_hresampled_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S height_val7_c19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_hcresampler_core_U0_height_val7_c19_din),
    .if_full_n(height_val7_c19_full_n),
    .if_write(v_hcresampler_core_U0_height_val7_c19_write),
    .if_dout(height_val7_c19_dout),
    .if_num_data_valid(height_val7_c19_num_data_valid),
    .if_fifo_cap(height_val7_c19_fifo_cap),
    .if_empty_n(height_val7_c19_empty_n),
    .if_read(v_vcresampler_core_U0_height_val7_read)
);

design_1_v_tpg_0_0_fifo_w16_d2_S width_val12_c22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_hcresampler_core_U0_width_val12_c22_din),
    .if_full_n(width_val12_c22_full_n),
    .if_write(v_hcresampler_core_U0_width_val12_c22_write),
    .if_dout(width_val12_c22_dout),
    .if_num_data_valid(width_val12_c22_num_data_valid),
    .if_fifo_cap(width_val12_c22_fifo_cap),
    .if_empty_n(width_val12_c22_empty_n),
    .if_read(v_vcresampler_core_U0_width_val12_read)
);

design_1_v_tpg_0_0_fifo_w1_d3_S bPassThru_1_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_return),
    .if_full_n(bPassThru_1_loc_channel_full_n),
    .if_write(v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_done),
    .if_dout(bPassThru_1_loc_channel_dout),
    .if_num_data_valid(bPassThru_1_loc_channel_num_data_valid),
    .if_fifo_cap(bPassThru_1_loc_channel_fifo_cap),
    .if_empty_n(bPassThru_1_loc_channel_empty_n),
    .if_read(v_vcresampler_core_U0_ap_ready)
);

design_1_v_tpg_0_0_fifo_w24_d2_S stream_out_vresampled_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_vcresampler_core_U0_stream_out_vresampled_din),
    .if_full_n(stream_out_vresampled_full_n),
    .if_write(v_vcresampler_core_U0_stream_out_vresampled_write),
    .if_dout(stream_out_vresampled_dout),
    .if_num_data_valid(stream_out_vresampled_num_data_valid),
    .if_fifo_cap(stream_out_vresampled_fifo_cap),
    .if_empty_n(stream_out_vresampled_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_stream_out_vresampled_read)
);

design_1_v_tpg_0_0_fifo_w12_d2_S height_val7_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_vcresampler_core_U0_height_val7_c_din),
    .if_full_n(height_val7_c_full_n),
    .if_write(v_vcresampler_core_U0_height_val7_c_write),
    .if_dout(height_val7_c_dout),
    .if_num_data_valid(height_val7_c_num_data_valid),
    .if_fifo_cap(height_val7_c_fifo_cap),
    .if_empty_n(height_val7_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_height_val7_read)
);

design_1_v_tpg_0_0_fifo_w13_d2_S width_val12_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(v_vcresampler_core_U0_width_val12_c_din),
    .if_full_n(width_val12_c_full_n),
    .if_write(v_vcresampler_core_U0_width_val12_c_write),
    .if_dout(width_val12_c_dout),
    .if_num_data_valid(width_val12_c_num_data_valid),
    .if_fifo_cap(width_val12_c_fifo_cap),
    .if_empty_n(width_val12_c_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_width_val12_read)
);

design_1_v_tpg_0_0_start_for_tpgForeground_U0 start_for_tpgForeground_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_tpgForeground_U0_din),
    .if_full_n(start_for_tpgForeground_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_tpgForeground_U0_dout),
    .if_empty_n(start_for_tpgForeground_U0_empty_n),
    .if_read(tpgForeground_U0_ap_ready)
);

design_1_v_tpg_0_0_start_for_MultiPixStream2AXIvideo_U0 start_for_MultiPixStream2AXIvideo_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_MultiPixStream2AXIvideo_U0_din),
    .if_full_n(start_for_MultiPixStream2AXIvideo_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_MultiPixStream2AXIvideo_U0_dout),
    .if_empty_n(start_for_MultiPixStream2AXIvideo_U0_empty_n),
    .if_read(MultiPixStream2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_bPassThru_loc_channel <= 1'b0;
    end else begin
        if (((v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_done & v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_bPassThru_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_bPassThru_loc_channel <= ap_sync_channel_write_bPassThru_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_icmp_ln377_1_loc_channel <= 1'b0;
    end else begin
        if (((v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_done & v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_icmp_ln377_1_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_icmp_ln377_1_loc_channel <= ap_sync_channel_write_icmp_ln377_1_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_tpgBackground_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_tpgBackground_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_tpgBackground_U0_ap_ready <= ap_sync_tpgBackground_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready <= ap_sync_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready;
        end
    end
end

assign MultiPixStream2AXIvideo_U0_ap_continue = ap_continue;

assign MultiPixStream2AXIvideo_U0_ap_start = start_for_MultiPixStream2AXIvideo_U0_empty_n;

assign ap_channel_done_bPassThru_loc_channel = (v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_done & (ap_sync_reg_channel_write_bPassThru_loc_channel ^ 1'b1));

assign ap_channel_done_icmp_ln377_1_loc_channel = (v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_done & (ap_sync_reg_channel_write_icmp_ln377_1_loc_channel ^ 1'b1));

assign ap_done = MultiPixStream2AXIvideo_U0_ap_done;

assign ap_idle = (v_vcresampler_core_U0_ap_idle & v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_idle & v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_idle & v_hcresampler_core_U0_ap_idle & tpgForeground_U0_ap_idle & tpgBackground_U0_ap_idle & (bPassThru_1_loc_channel_empty_n ^ 1'b1) & (bPassThru_loc_channel_empty_n ^ 1'b1) & (icmp_ln377_1_loc_channel_empty_n ^ 1'b1) & entry_proc_U0_ap_idle & MultiPixStream2AXIvideo_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_bPassThru_loc_channel = ((bPassThru_loc_channel_full_n & ap_channel_done_bPassThru_loc_channel) | ap_sync_reg_channel_write_bPassThru_loc_channel);

assign ap_sync_channel_write_icmp_ln377_1_loc_channel = ((icmp_ln377_1_loc_channel_full_n & ap_channel_done_icmp_ln377_1_loc_channel) | ap_sync_reg_channel_write_icmp_ln377_1_loc_channel);

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_ready = (ap_sync_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready & ap_sync_tpgBackground_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign ap_sync_tpgBackground_U0_ap_ready = (tpgBackground_U0_ap_ready | ap_sync_reg_tpgBackground_U0_ap_ready);

assign ap_sync_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready = (v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready | ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready);

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign entry_proc_U0_start_full_n = (start_for_tpgForeground_U0_full_n & start_for_MultiPixStream2AXIvideo_U0_full_n);

assign fid = MultiPixStream2AXIvideo_U0_fid;

assign fid_ap_vld = MultiPixStream2AXIvideo_U0_fid_ap_vld;

assign m_axis_video_TDATA = MultiPixStream2AXIvideo_U0_m_axis_video_TDATA;

assign m_axis_video_TDEST = MultiPixStream2AXIvideo_U0_m_axis_video_TDEST;

assign m_axis_video_TID = MultiPixStream2AXIvideo_U0_m_axis_video_TID;

assign m_axis_video_TKEEP = MultiPixStream2AXIvideo_U0_m_axis_video_TKEEP;

assign m_axis_video_TLAST = MultiPixStream2AXIvideo_U0_m_axis_video_TLAST;

assign m_axis_video_TSTRB = MultiPixStream2AXIvideo_U0_m_axis_video_TSTRB;

assign m_axis_video_TUSER = MultiPixStream2AXIvideo_U0_m_axis_video_TUSER;

assign m_axis_video_TVALID = MultiPixStream2AXIvideo_U0_m_axis_video_TVALID;

assign start_for_MultiPixStream2AXIvideo_U0_din = 1'b1;

assign start_for_tpgForeground_U0_din = 1'b1;

assign tpgBackground_U0_ap_continue = 1'b1;

assign tpgBackground_U0_ap_start = ((ap_sync_reg_tpgBackground_U0_ap_ready ^ 1'b1) & ap_start);

assign tpgForeground_U0_ap_continue = 1'b1;

assign tpgForeground_U0_ap_start = start_for_tpgForeground_U0_empty_n;

assign v_hcresampler_core_U0_ap_continue = 1'b1;

assign v_hcresampler_core_U0_ap_start = bPassThru_loc_channel_empty_n;

assign v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_continue = (ap_sync_channel_write_icmp_ln377_1_loc_channel & ap_sync_channel_write_bPassThru_loc_channel);

assign v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_start = ((ap_sync_reg_v_tpgHlsDataFlow_Block_entry36_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_continue = bPassThru_1_loc_channel_full_n;

assign v_tpgHlsDataFlow_Block_entry38_proc_U0_ap_start = icmp_ln377_1_loc_channel_empty_n;

assign v_vcresampler_core_U0_ap_continue = 1'b1;

assign v_vcresampler_core_U0_ap_start = bPassThru_1_loc_channel_empty_n;

endmodule //design_1_v_tpg_0_0_v_tpgHlsDataFlow
