// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_v_hcresampler_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        ovrlayYUV_dout,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        ovrlayYUV_empty_n,
        ovrlayYUV_read,
        height_val7_dout,
        height_val7_num_data_valid,
        height_val7_fifo_cap,
        height_val7_empty_n,
        height_val7_read,
        width_val12_dout,
        width_val12_num_data_valid,
        width_val12_fifo_cap,
        width_val12_empty_n,
        width_val12_read,
        p_read,
        stream_out_hresampled_din,
        stream_out_hresampled_num_data_valid,
        stream_out_hresampled_fifo_cap,
        stream_out_hresampled_full_n,
        stream_out_hresampled_write,
        height_val7_c19_din,
        height_val7_c19_num_data_valid,
        height_val7_c19_fifo_cap,
        height_val7_c19_full_n,
        height_val7_c19_write,
        width_val12_c22_din,
        width_val12_c22_num_data_valid,
        width_val12_c22_fifo_cap,
        width_val12_c22_full_n,
        width_val12_c22_write
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] ovrlayYUV_dout;
input  [4:0] ovrlayYUV_num_data_valid;
input  [4:0] ovrlayYUV_fifo_cap;
input   ovrlayYUV_empty_n;
output   ovrlayYUV_read;
input  [15:0] height_val7_dout;
input  [2:0] height_val7_num_data_valid;
input  [2:0] height_val7_fifo_cap;
input   height_val7_empty_n;
output   height_val7_read;
input  [15:0] width_val12_dout;
input  [2:0] width_val12_num_data_valid;
input  [2:0] width_val12_fifo_cap;
input   width_val12_empty_n;
output   width_val12_read;
input  [0:0] p_read;
output  [23:0] stream_out_hresampled_din;
input  [2:0] stream_out_hresampled_num_data_valid;
input  [2:0] stream_out_hresampled_fifo_cap;
input   stream_out_hresampled_full_n;
output   stream_out_hresampled_write;
output  [15:0] height_val7_c19_din;
input  [2:0] height_val7_c19_num_data_valid;
input  [2:0] height_val7_c19_fifo_cap;
input   height_val7_c19_full_n;
output   height_val7_c19_write;
output  [15:0] width_val12_c22_din;
input  [2:0] width_val12_c22_num_data_valid;
input  [2:0] width_val12_c22_fifo_cap;
input   width_val12_c22_full_n;
output   width_val12_c22_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg ovrlayYUV_read;
reg height_val7_read;
reg width_val12_read;
reg stream_out_hresampled_write;
reg height_val7_c19_write;
reg width_val12_c22_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    height_val7_blk_n;
reg    width_val12_blk_n;
reg    height_val7_c19_blk_n;
reg    width_val12_c22_blk_n;
reg    ap_block_state1;
reg   [15:0] width_val12_read_reg_501;
reg   [15:0] loopHeight_reg_507;
wire   [1:0] select_ln2047_fu_231_p3;
reg   [1:0] select_ln2047_reg_512;
wire    ap_CS_fsm_state2;
wire   [15:0] loopWidth_fu_245_p2;
reg   [15:0] loopWidth_reg_517;
wire   [0:0] not_bPassThru_i_fu_250_p2;
reg   [0:0] not_bPassThru_i_reg_522;
wire   [0:0] cmp36580_i_fu_255_p2;
reg   [0:0] cmp36580_i_reg_527;
reg   [7:0] pixbuf_y_1_load_reg_537;
wire    ap_CS_fsm_state3;
reg   [7:0] pixbuf_y_2_load_reg_542;
reg   [7:0] pixbuf_y_3_load_reg_547;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_idle;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_ready;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read;
wire   [23:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_din;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o_ap_vld;
wire   [7:0] grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o;
wire    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o_ap_vld;
reg    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [7:0] pixbuf_y_3_fu_136;
reg   [7:0] pixbuf_y_2_fu_132;
reg   [7:0] pixbuf_y_1_fu_128;
reg   [7:0] pixbuf_y_fu_124;
reg   [7:0] p_lcssa600641_i_fu_112;
reg   [7:0] p_lcssa599638_i_fu_108;
reg   [7:0] p_lcssa597632_i_fu_104;
reg   [7:0] p_lcssa627_i_fu_100;
reg   [7:0] inpix_0_2_0_0_0_load589_lcssa615_i_fu_84;
reg   [7:0] inpix_0_1_0_0_0_load587_lcssa612_i_fu_80;
reg   [7:0] inpix_0_0_0_0_0_load585_lcssa609_i_fu_76;
reg   [14:0] y_2_fu_72;
wire   [14:0] add_ln2049_fu_273_p2;
wire   [0:0] icmp_ln2049_fu_268_p2;
reg   [7:0] p_0_0_0_0_0450591_lcssa618_i_fu_88;
wire   [7:0] select_ln2028_2_fu_338_p3;
wire    ap_CS_fsm_state6;
reg   [7:0] p_0_1_0_0_0593_lcssa621_i_fu_92;
wire   [7:0] select_ln2028_1_fu_332_p3;
reg   [7:0] p_0_2_0_0_0595_lcssa624_i_fu_96;
wire   [7:0] select_ln2028_fu_326_p3;
reg   [7:0] p_0_1_0_0_0593602_lcssa644_i_fu_116;
reg   [7:0] p_0_2_0_0_0595605_lcssa647_i_fu_120;
reg   [7:0] pixbuf_y_4_fu_140;
wire   [15:0] select_ln2047_1_fu_238_p3;
wire   [15:0] zext_ln2049_fu_264_p1;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 6'd1;
#0 grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg = 1'b0;
#0 y_2_fu_72 = 15'd0;
#0 p_0_0_0_0_0450591_lcssa618_i_fu_88 = 8'd0;
#0 p_0_1_0_0_0593_lcssa621_i_fu_92 = 8'd0;
#0 p_0_2_0_0_0595_lcssa624_i_fu_96 = 8'd0;
#0 p_0_1_0_0_0593602_lcssa644_i_fu_116 = 8'd0;
#0 p_0_2_0_0_0595605_lcssa647_i_fu_120 = 8'd0;
#0 pixbuf_y_4_fu_140 = 8'd0;
end

design_1_v_tpg_0_0_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2 grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start),
    .ap_done(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done),
    .ap_idle(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_idle),
    .ap_ready(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_ready),
    .ovrlayYUV_dout(ovrlayYUV_dout),
    .ovrlayYUV_num_data_valid(5'd0),
    .ovrlayYUV_fifo_cap(5'd0),
    .ovrlayYUV_empty_n(ovrlayYUV_empty_n),
    .ovrlayYUV_read(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read),
    .stream_out_hresampled_din(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_din),
    .stream_out_hresampled_num_data_valid(3'd0),
    .stream_out_hresampled_fifo_cap(3'd0),
    .stream_out_hresampled_full_n(stream_out_hresampled_full_n),
    .stream_out_hresampled_write(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write),
    .pixbuf_y_4(pixbuf_y_4_fu_140),
    .pixbuf_y_3(pixbuf_y_3_load_reg_547),
    .pixbuf_y_2(pixbuf_y_2_load_reg_542),
    .pixbuf_y_1(pixbuf_y_1_load_reg_537),
    .p_0_2_0_0_0595605_lcssa647_i(p_0_2_0_0_0595605_lcssa647_i_fu_120),
    .p_0_1_0_0_0593602_lcssa644_i(p_0_1_0_0_0593602_lcssa644_i_fu_116),
    .p_0_2_0_0_0595_lcssa624_i(p_0_2_0_0_0595_lcssa624_i_fu_96),
    .p_0_1_0_0_0593_lcssa621_i(p_0_1_0_0_0593_lcssa621_i_fu_92),
    .p_0_0_0_0_0450591_lcssa618_i(p_0_0_0_0_0450591_lcssa618_i_fu_88),
    .loopWidth(loopWidth_reg_517),
    .p_read(p_read),
    .p_cast21_i(not_bPassThru_i_reg_522),
    .select_ln2047(select_ln2047_reg_512),
    .width_val12_load(width_val12_read_reg_501),
    .pixbuf_y_9_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out),
    .pixbuf_y_9_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out_ap_vld),
    .pixbuf_y_8_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out),
    .pixbuf_y_8_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out_ap_vld),
    .pixbuf_y_7_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out),
    .pixbuf_y_7_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out_ap_vld),
    .pixbuf_y_6_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out),
    .pixbuf_y_6_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out_ap_vld),
    .pixbuf_y_5_out_i(pixbuf_y_fu_124),
    .pixbuf_y_5_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o),
    .pixbuf_y_5_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o_ap_vld),
    .p_0_2_0_0_0595604_i_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out),
    .p_0_2_0_0_0595604_i_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out_ap_vld),
    .p_0_1_0_0_0593601_i_out(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out),
    .p_0_1_0_0_0593601_i_out_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out_ap_vld),
    .p_out_i(p_lcssa600641_i_fu_112),
    .p_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o),
    .p_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o_ap_vld),
    .p_out1_i(p_lcssa599638_i_fu_108),
    .p_out1_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o),
    .p_out1_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o_ap_vld),
    .p_out2_i(p_lcssa597632_i_fu_104),
    .p_out2_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o),
    .p_out2_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o_ap_vld),
    .p_out3_i(p_lcssa627_i_fu_100),
    .p_out3_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o),
    .p_out3_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o_ap_vld),
    .inpix_0_2_0_0_0_load588_i_out_i(inpix_0_2_0_0_0_load589_lcssa615_i_fu_84),
    .inpix_0_2_0_0_0_load588_i_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o),
    .inpix_0_2_0_0_0_load588_i_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o_ap_vld),
    .inpix_0_1_0_0_0_load586_i_out_i(inpix_0_1_0_0_0_load587_lcssa612_i_fu_80),
    .inpix_0_1_0_0_0_load586_i_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o),
    .inpix_0_1_0_0_0_load586_i_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o_ap_vld),
    .inpix_0_0_0_0_0_load584_i_out_i(inpix_0_0_0_0_0_load585_lcssa609_i_fu_76),
    .inpix_0_0_0_0_0_load584_i_out_o(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o),
    .inpix_0_0_0_0_0_load584_i_out_o_ap_vld(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln2049_fu_268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg <= 1'b1;
        end else if ((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_ready == 1'b1)) begin
            grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_2_fu_72 <= 15'd0;
    end else if (((icmp_ln2049_fu_268_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        y_2_fu_72 <= add_ln2049_fu_273_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp36580_i_reg_527 <= cmp36580_i_fu_255_p2;
        loopWidth_reg_517 <= loopWidth_fu_245_p2;
        not_bPassThru_i_reg_522 <= not_bPassThru_i_fu_250_p2;
        select_ln2047_reg_512[1] <= select_ln2047_fu_231_p3[1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o_ap_vld == 1'b1))) begin
        inpix_0_0_0_0_0_load585_lcssa609_i_fu_76 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o_ap_vld == 1'b1))) begin
        inpix_0_1_0_0_0_load587_lcssa612_i_fu_80 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o_ap_vld == 1'b1))) begin
        inpix_0_2_0_0_0_load589_lcssa615_i_fu_84 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        loopHeight_reg_507 <= height_val7_dout;
        width_val12_read_reg_501 <= width_val12_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        p_0_0_0_0_0450591_lcssa618_i_fu_88 <= select_ln2028_2_fu_338_p3;
        p_0_1_0_0_0593602_lcssa644_i_fu_116 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out;
        p_0_1_0_0_0593_lcssa621_i_fu_92 <= select_ln2028_1_fu_332_p3;
        p_0_2_0_0_0595605_lcssa647_i_fu_120 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out;
        p_0_2_0_0_0595_lcssa624_i_fu_96 <= select_ln2028_fu_326_p3;
        pixbuf_y_4_fu_140 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o_ap_vld == 1'b1))) begin
        p_lcssa597632_i_fu_104 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o_ap_vld == 1'b1))) begin
        p_lcssa599638_i_fu_108 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o_ap_vld == 1'b1))) begin
        p_lcssa600641_i_fu_112 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o_ap_vld == 1'b1))) begin
        p_lcssa627_i_fu_100 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out_ap_vld == 1'b1))) begin
        pixbuf_y_1_fu_128 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        pixbuf_y_1_load_reg_537 <= pixbuf_y_1_fu_128;
        pixbuf_y_2_load_reg_542 <= pixbuf_y_2_fu_132;
        pixbuf_y_3_load_reg_547 <= pixbuf_y_3_fu_136;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out_ap_vld == 1'b1))) begin
        pixbuf_y_2_fu_132 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out_ap_vld == 1'b1))) begin
        pixbuf_y_3_fu_136 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o_ap_vld == 1'b1))) begin
        pixbuf_y_fu_124 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln2049_fu_268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2049_fu_268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val7_blk_n = height_val7_empty_n;
    end else begin
        height_val7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val7_c19_blk_n = height_val7_c19_full_n;
    end else begin
        height_val7_c19_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val7_c19_write = 1'b1;
    end else begin
        height_val7_c19_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val7_read = 1'b1;
    end else begin
        height_val7_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ovrlayYUV_read = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read;
    end else begin
        ovrlayYUV_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        stream_out_hresampled_write = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write;
    end else begin
        stream_out_hresampled_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val12_blk_n = width_val12_empty_n;
    end else begin
        width_val12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val12_c22_blk_n = width_val12_c22_full_n;
    end else begin
        width_val12_c22_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val12_c22_write = 1'b1;
    end else begin
        width_val12_c22_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val12_read = 1'b1;
    end else begin
        width_val12_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln2049_fu_268_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2049_fu_273_p2 = (y_2_fu_72 + 15'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

always @ (*) begin
    ap_block_state1 = ((width_val12_c22_full_n == 1'b0) | (height_val7_c19_full_n == 1'b0) | (width_val12_empty_n == 1'b0) | (height_val7_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign cmp36580_i_fu_255_p2 = (($signed(loopWidth_fu_245_p2) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg;

assign height_val7_c19_din = height_val7_dout;

assign icmp_ln2049_fu_268_p2 = (($signed(zext_ln2049_fu_264_p1) < $signed(loopHeight_reg_507)) ? 1'b1 : 1'b0);

assign loopWidth_fu_245_p2 = (width_val12_read_reg_501 + select_ln2047_1_fu_238_p3);

assign not_bPassThru_i_fu_250_p2 = (p_read ^ 1'd1);

assign select_ln2028_1_fu_332_p3 = ((cmp36580_i_reg_527[0:0] == 1'b1) ? grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out : p_0_1_0_0_0593_lcssa621_i_fu_92);

assign select_ln2028_2_fu_338_p3 = ((cmp36580_i_reg_527[0:0] == 1'b1) ? grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out : p_0_0_0_0_0450591_lcssa618_i_fu_88);

assign select_ln2028_fu_326_p3 = ((cmp36580_i_reg_527[0:0] == 1'b1) ? grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out : p_0_2_0_0_0595_lcssa624_i_fu_96);

assign select_ln2047_1_fu_238_p3 = ((p_read[0:0] == 1'b1) ? 16'd0 : 16'd2);

assign select_ln2047_fu_231_p3 = ((p_read[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign stream_out_hresampled_din = grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_din;

assign width_val12_c22_din = width_val12_dout;

assign zext_ln2049_fu_264_p1 = y_2_fu_72;

always @ (posedge ap_clk) begin
    select_ln2047_reg_512[0] <= 1'b0;
end

endmodule //design_1_v_tpg_0_0_v_hcresampler_core
