set_property PACKAGE_PIN E15 [get_ports compare_done]
set_property PACKAGE_PIN D15 [get_ports error_flag]
set_property IOSTANDARD LVCMOS18 [get_ports compare_done]
set_property IOSTANDARD LVCMOS18 [get_ports error_flag]
set_property PACKAGE_PIN F19 [get_ports key_in]
set_property IOSTANDARD LVCMOS18 [get_ports key_in]
