# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: c:/Vulcan/FPGA/Vivado_Lab/Debug_Tool/ibert_7series_gtx_0_ex/imports/example_ibert_7series_gtx_0.xdc

# IP: ip/ibert_7series_gtx_0/ibert_7series_gtx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ibert_7series_gtx_0 || ORIG_REF_NAME==ibert_7series_gtx_0} -quiet] -quiet

# XDC: c:/Vulcan/FPGA/Vivado_Lab/Debug_Tool/ibert_7series_gtx_0_ex/ibert_7series_gtx_0_ex.gen/sources_1/ip/ibert_7series_gtx_0/synth/ibert_waivers.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ibert_7series_gtx_0 || ORIG_REF_NAME==ibert_7series_gtx_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
