# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Adder/Adder.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder || ORIG_REF_NAME==Adder} -quiet] -quiet

# IP: bd/Adder/ip/Adder_example_0_0/Adder_example_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_example_0_0 || ORIG_REF_NAME==Adder_example_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_processing_system7_0_0/Adder_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_processing_system7_0_0 || ORIG_REF_NAME==Adder_processing_system7_0_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_ps7_0_axi_periph_0/Adder_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_ps7_0_axi_periph_0 || ORIG_REF_NAME==Adder_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_rst_ps7_0_50M_0/Adder_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_rst_ps7_0_50M_0 || ORIG_REF_NAME==Adder_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Adder/ip/Adder_auto_pc_0/Adder_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Adder_auto_pc_0 || ORIG_REF_NAME==Adder_auto_pc_0} -quiet] -quiet

# XDC: c:/va/z702/Adder/Adder.gen/sources_1/bd/Adder/Adder_ooc.xdc
