-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity design_1_v_tpg_0_0_v_hcresampler_core is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ovrlayYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_empty_n : IN STD_LOGIC;
    ovrlayYUV_read : OUT STD_LOGIC;
    height_val7_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    height_val7_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_empty_n : IN STD_LOGIC;
    height_val7_read : OUT STD_LOGIC;
    width_val12_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val12_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_empty_n : IN STD_LOGIC;
    width_val12_read : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (0 downto 0);
    stream_out_hresampled_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    stream_out_hresampled_full_n : IN STD_LOGIC;
    stream_out_hresampled_write : OUT STD_LOGIC;
    height_val7_c19_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    height_val7_c19_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_c19_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val7_c19_full_n : IN STD_LOGIC;
    height_val7_c19_write : OUT STD_LOGIC;
    width_val12_c22_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    width_val12_c22_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_c22_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val12_c22_full_n : IN STD_LOGIC;
    width_val12_c22_write : OUT STD_LOGIC );
end;


architecture behav of design_1_v_tpg_0_0_v_hcresampler_core is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv15_1 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal height_val7_blk_n : STD_LOGIC;
    signal width_val12_blk_n : STD_LOGIC;
    signal height_val7_c19_blk_n : STD_LOGIC;
    signal width_val12_c22_blk_n : STD_LOGIC;
    signal ap_block_state1 : BOOLEAN;
    signal width_val12_read_reg_501 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopHeight_reg_507 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln2047_fu_231_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln2047_reg_512 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal loopWidth_fu_245_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal loopWidth_reg_517 : STD_LOGIC_VECTOR (15 downto 0);
    signal not_bPassThru_i_fu_250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_bPassThru_i_reg_522 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp36580_i_fu_255_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp36580_i_reg_527 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixbuf_y_1_load_reg_537 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal pixbuf_y_2_load_reg_542 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_3_load_reg_547 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_idle : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_ready : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_din : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o_ap_vld : STD_LOGIC;
    signal grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal pixbuf_y_3_fu_136 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_2_fu_132 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_1_fu_128 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixbuf_y_fu_124 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa600641_i_fu_112 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa599638_i_fu_108 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa597632_i_fu_104 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_lcssa627_i_fu_100 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_2_0_0_0_load589_lcssa615_i_fu_84 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_1_0_0_0_load587_lcssa612_i_fu_80 : STD_LOGIC_VECTOR (7 downto 0);
    signal inpix_0_0_0_0_0_load585_lcssa609_i_fu_76 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_2_fu_72 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    signal add_ln2049_fu_273_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln2049_fu_268_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_0_0_0_0_0450591_lcssa618_i_fu_88 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln2028_2_fu_338_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal p_0_1_0_0_0593_lcssa621_i_fu_92 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln2028_1_fu_332_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_2_0_0_0595_lcssa624_i_fu_96 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln2028_fu_326_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_1_0_0_0593602_lcssa644_i_fu_116 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal p_0_2_0_0_0595605_lcssa647_i_fu_120 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal pixbuf_y_4_fu_140 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln2047_1_fu_238_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln2049_fu_264_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component design_1_v_tpg_0_0_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ovrlayYUV_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        ovrlayYUV_empty_n : IN STD_LOGIC;
        ovrlayYUV_read : OUT STD_LOGIC;
        stream_out_hresampled_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        stream_out_hresampled_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_out_hresampled_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        stream_out_hresampled_full_n : IN STD_LOGIC;
        stream_out_hresampled_write : OUT STD_LOGIC;
        pixbuf_y_4 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_3 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_2 : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_1 : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0595605_lcssa647_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0593602_lcssa644_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0595_lcssa624_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0593_lcssa621_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_0_0_0_0_0450591_lcssa618_i : IN STD_LOGIC_VECTOR (7 downto 0);
        loopWidth : IN STD_LOGIC_VECTOR (15 downto 0);
        p_read : IN STD_LOGIC_VECTOR (0 downto 0);
        p_cast21_i : IN STD_LOGIC_VECTOR (0 downto 0);
        select_ln2047 : IN STD_LOGIC_VECTOR (1 downto 0);
        width_val12_load : IN STD_LOGIC_VECTOR (15 downto 0);
        pixbuf_y_9_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_9_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_8_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_8_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_7_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_7_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_6_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_6_out_ap_vld : OUT STD_LOGIC;
        pixbuf_y_5_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_5_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        pixbuf_y_5_out_o_ap_vld : OUT STD_LOGIC;
        p_0_2_0_0_0595604_i_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_2_0_0_0595604_i_out_ap_vld : OUT STD_LOGIC;
        p_0_1_0_0_0593601_i_out : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_0_1_0_0_0593601_i_out_ap_vld : OUT STD_LOGIC;
        p_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out_o_ap_vld : OUT STD_LOGIC;
        p_out1_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out1_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out1_o_ap_vld : OUT STD_LOGIC;
        p_out2_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out2_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out2_o_ap_vld : OUT STD_LOGIC;
        p_out3_i : IN STD_LOGIC_VECTOR (7 downto 0);
        p_out3_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_out3_o_ap_vld : OUT STD_LOGIC;
        inpix_0_2_0_0_0_load588_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_2_0_0_0_load588_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_2_0_0_0_load588_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_1_0_0_0_load586_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_1_0_0_0_load586_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_1_0_0_0_load586_i_out_o_ap_vld : OUT STD_LOGIC;
        inpix_0_0_0_0_0_load584_i_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_0_0_0_0_load584_i_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        inpix_0_0_0_0_0_load584_i_out_o_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190 : component design_1_v_tpg_0_0_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start,
        ap_done => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done,
        ap_idle => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_idle,
        ap_ready => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_ready,
        ovrlayYUV_dout => ovrlayYUV_dout,
        ovrlayYUV_num_data_valid => ap_const_lv5_0,
        ovrlayYUV_fifo_cap => ap_const_lv5_0,
        ovrlayYUV_empty_n => ovrlayYUV_empty_n,
        ovrlayYUV_read => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read,
        stream_out_hresampled_din => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_din,
        stream_out_hresampled_num_data_valid => ap_const_lv3_0,
        stream_out_hresampled_fifo_cap => ap_const_lv3_0,
        stream_out_hresampled_full_n => stream_out_hresampled_full_n,
        stream_out_hresampled_write => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write,
        pixbuf_y_4 => pixbuf_y_4_fu_140,
        pixbuf_y_3 => pixbuf_y_3_load_reg_547,
        pixbuf_y_2 => pixbuf_y_2_load_reg_542,
        pixbuf_y_1 => pixbuf_y_1_load_reg_537,
        p_0_2_0_0_0595605_lcssa647_i => p_0_2_0_0_0595605_lcssa647_i_fu_120,
        p_0_1_0_0_0593602_lcssa644_i => p_0_1_0_0_0593602_lcssa644_i_fu_116,
        p_0_2_0_0_0595_lcssa624_i => p_0_2_0_0_0595_lcssa624_i_fu_96,
        p_0_1_0_0_0593_lcssa621_i => p_0_1_0_0_0593_lcssa621_i_fu_92,
        p_0_0_0_0_0450591_lcssa618_i => p_0_0_0_0_0450591_lcssa618_i_fu_88,
        loopWidth => loopWidth_reg_517,
        p_read => p_read,
        p_cast21_i => not_bPassThru_i_reg_522,
        select_ln2047 => select_ln2047_reg_512,
        width_val12_load => width_val12_read_reg_501,
        pixbuf_y_9_out => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out,
        pixbuf_y_9_out_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out_ap_vld,
        pixbuf_y_8_out => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out,
        pixbuf_y_8_out_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out_ap_vld,
        pixbuf_y_7_out => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out,
        pixbuf_y_7_out_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out_ap_vld,
        pixbuf_y_6_out => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out,
        pixbuf_y_6_out_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out_ap_vld,
        pixbuf_y_5_out_i => pixbuf_y_fu_124,
        pixbuf_y_5_out_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o,
        pixbuf_y_5_out_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o_ap_vld,
        p_0_2_0_0_0595604_i_out => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out,
        p_0_2_0_0_0595604_i_out_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out_ap_vld,
        p_0_1_0_0_0593601_i_out => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out,
        p_0_1_0_0_0593601_i_out_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out_ap_vld,
        p_out_i => p_lcssa600641_i_fu_112,
        p_out_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o,
        p_out_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o_ap_vld,
        p_out1_i => p_lcssa599638_i_fu_108,
        p_out1_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o,
        p_out1_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o_ap_vld,
        p_out2_i => p_lcssa597632_i_fu_104,
        p_out2_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o,
        p_out2_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o_ap_vld,
        p_out3_i => p_lcssa627_i_fu_100,
        p_out3_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o,
        p_out3_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o_ap_vld,
        inpix_0_2_0_0_0_load588_i_out_i => inpix_0_2_0_0_0_load589_lcssa615_i_fu_84,
        inpix_0_2_0_0_0_load588_i_out_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o,
        inpix_0_2_0_0_0_load588_i_out_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o_ap_vld,
        inpix_0_1_0_0_0_load586_i_out_i => inpix_0_1_0_0_0_load587_lcssa612_i_fu_80,
        inpix_0_1_0_0_0_load586_i_out_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o,
        inpix_0_1_0_0_0_load586_i_out_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o_ap_vld,
        inpix_0_0_0_0_0_load584_i_out_i => inpix_0_0_0_0_0_load585_lcssa609_i_fu_76,
        inpix_0_0_0_0_0_load584_i_out_o => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o,
        inpix_0_0_0_0_0_load584_i_out_o_ap_vld => grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln2049_fu_268_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_ready = ap_const_logic_1)) then 
                    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_2_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_2_fu_72 <= ap_const_lv15_0;
            elsif (((icmp_ln2049_fu_268_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                y_2_fu_72 <= add_ln2049_fu_273_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp36580_i_reg_527 <= cmp36580_i_fu_255_p2;
                loopWidth_reg_517 <= loopWidth_fu_245_p2;
                not_bPassThru_i_reg_522 <= not_bPassThru_i_fu_250_p2;
                    select_ln2047_reg_512(1) <= select_ln2047_fu_231_p3(1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_0_0_0_0_load585_lcssa609_i_fu_76 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_0_0_0_0_load584_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_1_0_0_0_load587_lcssa612_i_fu_80 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_1_0_0_0_load586_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o_ap_vld = ap_const_logic_1))) then
                inpix_0_2_0_0_0_load589_lcssa615_i_fu_84 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_inpix_0_2_0_0_0_load588_i_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                loopHeight_reg_507 <= height_val7_dout;
                width_val12_read_reg_501 <= width_val12_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                p_0_0_0_0_0450591_lcssa618_i_fu_88 <= select_ln2028_2_fu_338_p3;
                p_0_1_0_0_0593602_lcssa644_i_fu_116 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out;
                p_0_1_0_0_0593_lcssa621_i_fu_92 <= select_ln2028_1_fu_332_p3;
                p_0_2_0_0_0595605_lcssa647_i_fu_120 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out;
                p_0_2_0_0_0595_lcssa624_i_fu_96 <= select_ln2028_fu_326_p3;
                pixbuf_y_4_fu_140 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o_ap_vld = ap_const_logic_1))) then
                p_lcssa597632_i_fu_104 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out2_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o_ap_vld = ap_const_logic_1))) then
                p_lcssa599638_i_fu_108 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out1_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o_ap_vld = ap_const_logic_1))) then
                p_lcssa600641_i_fu_112 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o_ap_vld = ap_const_logic_1))) then
                p_lcssa627_i_fu_100 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_out3_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out_ap_vld = ap_const_logic_1))) then
                pixbuf_y_1_fu_128 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_6_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                pixbuf_y_1_load_reg_537 <= pixbuf_y_1_fu_128;
                pixbuf_y_2_load_reg_542 <= pixbuf_y_2_fu_132;
                pixbuf_y_3_load_reg_547 <= pixbuf_y_3_fu_136;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out_ap_vld = ap_const_logic_1))) then
                pixbuf_y_2_fu_132 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_7_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out_ap_vld = ap_const_logic_1))) then
                pixbuf_y_3_fu_136 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_8_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o_ap_vld = ap_const_logic_1))) then
                pixbuf_y_fu_124 <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_5_out_o;
            end if;
        end if;
    end process;
    select_ln2047_reg_512(0) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state3, grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done, ap_CS_fsm_state5, icmp_ln2049_fu_268_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln2049_fu_268_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln2049_fu_273_p2 <= std_logic_vector(unsigned(y_2_fu_72) + unsigned(ap_const_lv15_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done)
    begin
        if ((grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val7_empty_n, width_val12_empty_n, height_val7_c19_full_n, width_val12_c22_full_n)
    begin
                ap_block_state1 <= ((width_val12_c22_full_n = ap_const_logic_0) or (height_val7_c19_full_n = ap_const_logic_0) or (width_val12_empty_n = ap_const_logic_0) or (height_val7_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln2049_fu_268_p2)
    begin
        if (((icmp_ln2049_fu_268_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln2049_fu_268_p2)
    begin
        if (((icmp_ln2049_fu_268_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp36580_i_fu_255_p2 <= "1" when (signed(loopWidth_fu_245_p2) > signed(ap_const_lv16_0)) else "0";
    grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ap_start_reg;

    height_val7_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val7_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val7_blk_n <= height_val7_empty_n;
        else 
            height_val7_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    height_val7_c19_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val7_c19_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val7_c19_blk_n <= height_val7_c19_full_n;
        else 
            height_val7_c19_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val7_c19_din <= height_val7_dout;

    height_val7_c19_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val7_c19_write <= ap_const_logic_1;
        else 
            height_val7_c19_write <= ap_const_logic_0;
        end if; 
    end process;


    height_val7_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val7_read <= ap_const_logic_1;
        else 
            height_val7_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln2049_fu_268_p2 <= "1" when (signed(zext_ln2049_fu_264_p1) < signed(loopHeight_reg_507)) else "0";
    loopWidth_fu_245_p2 <= std_logic_vector(unsigned(width_val12_read_reg_501) + unsigned(select_ln2047_1_fu_238_p3));
    not_bPassThru_i_fu_250_p2 <= (p_read xor ap_const_lv1_1);

    ovrlayYUV_read_assign_proc : process(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ovrlayYUV_read <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_ovrlayYUV_read;
        else 
            ovrlayYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln2028_1_fu_332_p3 <= 
        grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_1_0_0_0593601_i_out when (cmp36580_i_reg_527(0) = '1') else 
        p_0_1_0_0_0593_lcssa621_i_fu_92;
    select_ln2028_2_fu_338_p3 <= 
        grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_pixbuf_y_9_out when (cmp36580_i_reg_527(0) = '1') else 
        p_0_0_0_0_0450591_lcssa618_i_fu_88;
    select_ln2028_fu_326_p3 <= 
        grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_p_0_2_0_0_0595604_i_out when (cmp36580_i_reg_527(0) = '1') else 
        p_0_2_0_0_0595_lcssa624_i_fu_96;
    select_ln2047_1_fu_238_p3 <= 
        ap_const_lv16_0 when (p_read(0) = '1') else 
        ap_const_lv16_2;
    select_ln2047_fu_231_p3 <= 
        ap_const_lv2_0 when (p_read(0) = '1') else 
        ap_const_lv2_2;
    stream_out_hresampled_din <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_din;

    stream_out_hresampled_write_assign_proc : process(grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            stream_out_hresampled_write <= grp_v_hcresampler_core_Pipeline_VITIS_LOOP_2052_2_fu_190_stream_out_hresampled_write;
        else 
            stream_out_hresampled_write <= ap_const_logic_0;
        end if; 
    end process;


    width_val12_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val12_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val12_blk_n <= width_val12_empty_n;
        else 
            width_val12_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    width_val12_c22_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val12_c22_full_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val12_c22_blk_n <= width_val12_c22_full_n;
        else 
            width_val12_c22_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val12_c22_din <= width_val12_dout;

    width_val12_c22_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val12_c22_write <= ap_const_logic_1;
        else 
            width_val12_c22_write <= ap_const_logic_0;
        end if; 
    end process;


    width_val12_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val12_read <= ap_const_logic_1;
        else 
            width_val12_read <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln2049_fu_264_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_2_fu_72),16));
end behav;
