set_property SRC_FILE_INFO {cfile:c:/Vulcan/FPGA/Vivado_Lab/Debug_Tool/ibert_7series_gtx_0_ex/ibert_7series_gtx_0_ex.gen/sources_1/ip/ibert_7series_gtx_0/synth/ibert_waivers.xdc rfile:../../../ibert_7series_gtx_0_ex.gen/sources_1/ip/ibert_7series_gtx_0/synth/ibert_waivers.xdc id:1 order:EARLY scoped_inst:u_ibert_core/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Vulcan/FPGA/Vivado_Lab/Debug_Tool/ibert_7series_gtx_0_ex/imports/example_ibert_7series_gtx_0.xdc rfile:../../../imports/example_ibert_7series_gtx_0.xdc id:2} [current_design]
current_instance u_ibert_core/inst
set_property src_info {type:SCOPED_XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_STAT/stat_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/icn_cmd_dout_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/stat_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/icn_cmd_dout_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen32.patchk20/patgen_rx/pat_id_r1_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXUSRCLK*_FREQ_COUNTER/state_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXUSRCLK*_FREQ_COUNTER/testclk_cnt_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/ctl_reg_en_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*RXUSRCLK*} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/rxresetdone_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen32.patchk20/link_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXCDR_RESET/link_r_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen40.patchk40/link_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXCDR_RESET/link_r_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*RXUSRCLK*} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXCDR_RESET/rxresetdone_r_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*TXUSRCLK*} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/txresetdone_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_TXUSRCLK*_FREQ_COUNTER/state_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_TXUSRCLK*_FREQ_COUNTER/testclk_cnt_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/GTTXRESET_O_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen32.patgen32/init_r1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/GTTXRESET_O_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen40.patgen40/init_r1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/tei_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen32.patgen32/pat_id_r1_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen40.patchk40/patgen_rx/pat_id_r1_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-1} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-1 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen40.patgen40/pat_id_r1_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/ctl_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_RD/U_RD_FIFO/SUBCORE_FIFO.xsdb_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/ctl_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_WR/U_WR_FIFO/SUBCORE_FIFO.xsdb_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/mgt_reset_dly2_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXUSRCLK*_FREQ_COUNTER/rst_i_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/stat_reg_ld_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_RD/U_RD_FIFO/SUBCORE_FIFO.xsdb_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_WR/U_WR_FIFO/SUBCORE_FIFO.xsdb_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_STAT/stat_reg_ld_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/mgt_reset_dly2_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_TXUSRCLK*_FREQ_COUNTER/rst_i_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen32.patchk20/i_ones_counter/ANY_ONE_O_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/u_lev/out_i_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/gen40.patchk40/i_ones_counter/ANY_ONE_O_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/u_lev/out_i_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-10} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-10 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_PATTERN_HANDLER/u_lev/out_i_reg[*]}]]
set_property src_info {type:SCOPED_XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-11} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-11 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/ctl_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_RD/U_RD_FIFO/SUBCORE_FIFO.xsdb_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-11} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-11 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*/ctl_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_WR/U_WR_FIFO/SUBCORE_FIFO.xsdb_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-11} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-11 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/mgt_reset_dly2_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RXUSRCLK*_FREQ_COUNTER/rst_i_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-11} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-11 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_RESET_CONTROLLER/mgt_reset_dly2_reg}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_TXUSRCLK*_FREQ_COUNTER/rst_i_dly1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-11} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-11 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_RD/U_RD_FIFO/SUBCORE_FIFO.xsdb_rdfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_wr_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-11} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-11 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*U_ICON/U_CMD/iTARGET_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*PRE} -of_objects [get_cells -hierarchical -filter {NAME =~*UUT_MASTER/U_ICON_INTERFACE/U_CMD*_WR/U_WR_FIFO/SUBCORE_FIFO.xsdb_wrfifo_inst/inst_fifo_gen/gconvfifo.rf/grf.rf/rstblk/ngwrdrst.grst.g7serrst.rst_rd_reg1_reg}]]
set_property src_info {type:SCOPED_XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RX8B10BEN} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXCHBONDEN} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXCHBONDMASTER} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXCHBONDSLAVE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXCOMMADETEN} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXGEARBOXSLIP} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXMCOMMAALIGNEN} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXPCOMMAALIGNEN} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXPOLARITY} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXPRBSCNTRESET} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXSLIDE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*SETERRSTATUS} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXCHBONDI[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXCHBONDLEVEL[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TX8B10BEN} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXCOMINIT} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXCOMSAS} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXCOMWAKE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXDETECTRX} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXELECIDLE} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXINHIBIT} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXPOLARITY} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXPRBSFORCEERR} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXSTARTSEQ} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TX8B10BBYPASS[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXHEADER[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-13} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-13 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXPRBSSEL[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-14} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-14 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*RXPRBSSEL[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-14} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-14 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXPD[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
set_property src_info {type:SCOPED_XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -type CDC -id {CDC-14} -user ibert_ultrascale_gty -tags "1165961" -description "CDC-14 waiver for CPLL Calibration logic" -scope -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_*/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[*]}]] -to [get_pins -quiet -filter {REF_PIN_NAME=~*TXSEQUENCE[*]} -of_objects [get_cells -hierarchical -filter {NAME =~*QUAD[*].u_q/CH[*].u_ch/u_gtxe*_channel}]]
current_instance
set_property src_info {type:XDC file:2 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E19 [get_ports SYSCLKP_I]
set_property src_info {type:XDC file:2 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports SYSCLKN_I]
set_property src_info {type:XDC file:2 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y1 [get_cells u_ibert_core/inst/QUAD[0].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y2 [get_cells u_ibert_core/inst/QUAD[0].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y3 [get_cells u_ibert_core/inst/QUAD[0].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y4 [get_cells u_ibert_core/inst/QUAD[1].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y5 [get_cells u_ibert_core/inst/QUAD[1].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y6 [get_cells u_ibert_core/inst/QUAD[1].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y7 [get_cells u_ibert_core/inst/QUAD[1].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y1 [get_cells u_ibert_core/inst/QUAD[1].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y8 [get_cells u_ibert_core/inst/QUAD[2].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y9 [get_cells u_ibert_core/inst/QUAD[2].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y10 [get_cells u_ibert_core/inst/QUAD[2].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y11 [get_cells u_ibert_core/inst/QUAD[2].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y2 [get_cells u_ibert_core/inst/QUAD[2].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y12 [get_cells u_ibert_core/inst/QUAD[3].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y13 [get_cells u_ibert_core/inst/QUAD[3].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y14 [get_cells u_ibert_core/inst/QUAD[3].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y15 [get_cells u_ibert_core/inst/QUAD[3].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y3 [get_cells u_ibert_core/inst/QUAD[3].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y16 [get_cells u_ibert_core/inst/QUAD[4].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y17 [get_cells u_ibert_core/inst/QUAD[4].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y18 [get_cells u_ibert_core/inst/QUAD[4].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y19 [get_cells u_ibert_core/inst/QUAD[4].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y4 [get_cells u_ibert_core/inst/QUAD[4].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y20 [get_cells u_ibert_core/inst/QUAD[5].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y21 [get_cells u_ibert_core/inst/QUAD[5].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y22 [get_cells u_ibert_core/inst/QUAD[5].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y23 [get_cells u_ibert_core/inst/QUAD[5].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y5 [get_cells u_ibert_core/inst/QUAD[5].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y24 [get_cells u_ibert_core/inst/QUAD[6].u_q/CH[0].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y25 [get_cells u_ibert_core/inst/QUAD[6].u_q/CH[1].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y26 [get_cells u_ibert_core/inst/QUAD[6].u_q/CH[2].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_CHANNEL_X1Y27 [get_cells u_ibert_core/inst/QUAD[6].u_q/CH[3].u_ch/u_gtxe2_channel]
set_property src_info {type:XDC file:2 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTXE2_COMMON_X1Y6 [get_cells u_ibert_core/inst/QUAD[6].u_q/u_common/u_gtxe2_common]
set_property src_info {type:XDC file:2 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y0 [get_cells u_ibert_core/inst/QUAD[0].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y1 [get_cells u_ibert_core/inst/QUAD[0].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y2 [get_cells u_ibert_core/inst/QUAD[0].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y3 [get_cells u_ibert_core/inst/QUAD[0].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y4 [get_cells u_ibert_core/inst/QUAD[0].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y12 [get_cells u_ibert_core/inst/QUAD[1].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y13 [get_cells u_ibert_core/inst/QUAD[1].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y14 [get_cells u_ibert_core/inst/QUAD[1].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y15 [get_cells u_ibert_core/inst/QUAD[1].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y16 [get_cells u_ibert_core/inst/QUAD[1].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y24 [get_cells u_ibert_core/inst/QUAD[2].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y25 [get_cells u_ibert_core/inst/QUAD[2].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y26 [get_cells u_ibert_core/inst/QUAD[2].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y27 [get_cells u_ibert_core/inst/QUAD[2].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y28 [get_cells u_ibert_core/inst/QUAD[2].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y36 [get_cells u_ibert_core/inst/QUAD[3].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y37 [get_cells u_ibert_core/inst/QUAD[3].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y38 [get_cells u_ibert_core/inst/QUAD[3].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y39 [get_cells u_ibert_core/inst/QUAD[3].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y40 [get_cells u_ibert_core/inst/QUAD[3].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y48 [get_cells u_ibert_core/inst/QUAD[4].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y49 [get_cells u_ibert_core/inst/QUAD[4].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y50 [get_cells u_ibert_core/inst/QUAD[4].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y51 [get_cells u_ibert_core/inst/QUAD[4].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y52 [get_cells u_ibert_core/inst/QUAD[4].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y60 [get_cells u_ibert_core/inst/QUAD[5].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y61 [get_cells u_ibert_core/inst/QUAD[5].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y62 [get_cells u_ibert_core/inst/QUAD[5].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y63 [get_cells u_ibert_core/inst/QUAD[5].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y64 [get_cells u_ibert_core/inst/QUAD[5].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y72 [get_cells u_ibert_core/inst/QUAD[6].u_q/u_common/u_clocking/local_txusr.NON_K7.u_txusr]
set_property src_info {type:XDC file:2 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y73 [get_cells u_ibert_core/inst/QUAD[6].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr0]
set_property src_info {type:XDC file:2 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y74 [get_cells u_ibert_core/inst/QUAD[6].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr1]
set_property src_info {type:XDC file:2 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y75 [get_cells u_ibert_core/inst/QUAD[6].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr2]
set_property src_info {type:XDC file:2 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC BUFHCE_X1Y76 [get_cells u_ibert_core/inst/QUAD[6].u_q/u_common/u_clocking/rx_ind.NON_K7.u_rxusr3]
set_property src_info {type:XDC file:2 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y0 [get_cells u_buf_q9_clk0]
set_property src_info {type:XDC file:2 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y1 [get_cells u_buf_q9_clk1]
set_property src_info {type:XDC file:2 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y2 [get_cells u_buf_q10_clk0]
set_property src_info {type:XDC file:2 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y3 [get_cells u_buf_q10_clk1]
set_property src_info {type:XDC file:2 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y4 [get_cells u_buf_q11_clk0]
set_property src_info {type:XDC file:2 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y5 [get_cells u_buf_q11_clk1]
set_property src_info {type:XDC file:2 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y6 [get_cells u_buf_q12_clk0]
set_property src_info {type:XDC file:2 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y7 [get_cells u_buf_q12_clk1]
set_property src_info {type:XDC file:2 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y8 [get_cells u_buf_q13_clk0]
set_property src_info {type:XDC file:2 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y9 [get_cells u_buf_q13_clk1]
set_property src_info {type:XDC file:2 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y10 [get_cells u_buf_q14_clk0]
set_property src_info {type:XDC file:2 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y11 [get_cells u_buf_q14_clk1]
set_property src_info {type:XDC file:2 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y12 [get_cells u_buf_q15_clk0]
set_property src_info {type:XDC file:2 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC IBUFDS_GTE2_X1Y13 [get_cells u_buf_q15_clk1]
set_property src_info {type:XDC file:2 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[0].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[0].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[1].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[1].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[2].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[2].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[3].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[3].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[4].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[4].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[5].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[5].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[6].u_q/u_common/U_COMPLEX_REGS/reg_202/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
set_property src_info {type:XDC file:2 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[5]/Q}]
set_property src_info {type:XDC file:2 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[4]/Q}]
set_property src_info {type:XDC file:2 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_216/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[3]/Q}]
set_property src_info {type:XDC file:2 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[8]/Q}]
set_property src_info {type:XDC file:2 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[7]/Q}]
set_property src_info {type:XDC file:2 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[6]/Q}]
set_property src_info {type:XDC file:2 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[15]/Q}]
set_property src_info {type:XDC file:2 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[14]/Q}]
set_property src_info {type:XDC file:2 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_215/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[13]/Q}]
set_property src_info {type:XDC file:2 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[2]/Q}]
set_property src_info {type:XDC file:2 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[1]/Q}]
set_property src_info {type:XDC file:2 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {u_ibert_core/inst/QUAD[6].u_q/CH[*].u_ch/U_CHANNEL_REGS/reg_217/I_EN_CTL_EQ1.U_CTL/xsdb_reg_reg[0]/Q}]
