webtalk_init -webtalk_dir G:/V2020/S02/02_example_mig_ddr-35t/01_mig_ddr_test/mig_ddr_test/mig_ddr.sim/sim_1/behav/xsim/xsim.dir/sim_tb_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 14 22:49:55 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "71098800-368f-43a3-b2f6-a40bdae43016" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2a96f3c9076d4b04bc66da5f2a7a6934" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "140668317937 fs" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "246.30_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "82580_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2827440722 -regid "" -xml G:/V2020/S02/02_example_mig_ddr-35t/01_mig_ddr_test/mig_ddr_test/mig_ddr.sim/sim_1/behav/xsim/xsim.dir/sim_tb_top_behav/webtalk/usage_statistics_ext_xsim.xml -html G:/V2020/S02/02_example_mig_ddr-35t/01_mig_ddr_test/mig_ddr_test/mig_ddr.sim/sim_1/behav/xsim/xsim.dir/sim_tb_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm G:/V2020/S02/02_example_mig_ddr-35t/01_mig_ddr_test/mig_ddr_test/mig_ddr.sim/sim_1/behav/xsim/xsim.dir/sim_tb_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
