// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        height_val,
        width_val,
        patternId_val,
        ZplateHorContStart_val,
        ZplateHorContDelta_val,
        ZplateVerContStart_val,
        ZplateVerContDelta_val,
        dpYUVCoef_val,
        motionSpeed_val,
        bckgndYUV_din,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        bckgndYUV_full_n,
        bckgndYUV_write,
        height_val7_c21_din,
        height_val7_c21_num_data_valid,
        height_val7_c21_fifo_cap,
        height_val7_c21_full_n,
        height_val7_c21_write,
        width_val12_c24_din,
        width_val12_c24_num_data_valid,
        width_val12_c24_fifo_cap,
        width_val12_c24_full_n,
        width_val12_c24_write,
        motionSpeed_val19_c_din,
        motionSpeed_val19_c_num_data_valid,
        motionSpeed_val19_c_fifo_cap,
        motionSpeed_val19_c_full_n,
        motionSpeed_val19_c_write,
        s
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] height_val;
input  [15:0] width_val;
input  [7:0] patternId_val;
input  [15:0] ZplateHorContStart_val;
input  [15:0] ZplateHorContDelta_val;
input  [15:0] ZplateVerContStart_val;
input  [15:0] ZplateVerContDelta_val;
input  [7:0] dpYUVCoef_val;
input  [7:0] motionSpeed_val;
output  [23:0] bckgndYUV_din;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
output  [15:0] height_val7_c21_din;
input  [2:0] height_val7_c21_num_data_valid;
input  [2:0] height_val7_c21_fifo_cap;
input   height_val7_c21_full_n;
output   height_val7_c21_write;
output  [15:0] width_val12_c24_din;
input  [2:0] width_val12_c24_num_data_valid;
input  [2:0] width_val12_c24_fifo_cap;
input   width_val12_c24_full_n;
output   width_val12_c24_write;
output  [7:0] motionSpeed_val19_c_din;
input  [2:0] motionSpeed_val19_c_num_data_valid;
input  [2:0] motionSpeed_val19_c_fifo_cap;
input   motionSpeed_val19_c_full_n;
output   motionSpeed_val19_c_write;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg bckgndYUV_write;
reg height_val7_c21_write;
reg width_val12_c24_write;
reg motionSpeed_val19_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [7:0] rampStart;
reg   [15:0] rampVal_1;
reg   [7:0] rampVal;
reg   [7:0] hBarSel_4_0;
reg   [15:0] zonePlateVAddr;
reg   [2:0] vBarSel;
reg   [2:0] hBarSel_0;
reg   [15:0] hdata;
reg   [7:0] vBarSel_2;
reg   [2:0] hBarSel_3_0;
reg   [15:0] rampVal_2;
reg   [0:0] vBarSel_1;
reg   [2:0] hBarSel_5_0;
reg    height_val7_c21_blk_n;
reg    width_val12_c24_blk_n;
reg    motionSpeed_val19_c_blk_n;
reg    ap_block_state1;
reg   [7:0] rampStart_load_reg_1071;
reg   [10:0] barWidth_reg_1077;
wire   [7:0] empty_109_fu_573_p1;
reg   [7:0] empty_109_reg_1083;
wire   [9:0] barWidthMinSamples_fu_593_p2;
reg   [9:0] barWidthMinSamples_reg_1088;
wire   [15:0] shl_i_fu_613_p3;
reg   [15:0] shl_i_reg_1093;
wire   [10:0] sub_i_i_i_fu_635_p2;
reg   [10:0] sub_i_i_i_reg_1098;
wire   [16:0] sub35_i_fu_641_p2;
reg   [16:0] sub35_i_reg_1103;
wire   [16:0] sub10_i_fu_647_p2;
reg   [16:0] sub10_i_reg_1108;
wire   [0:0] cmp121_i_fu_653_p2;
reg   [0:0] cmp121_i_reg_1113;
reg   [15:0] y_4_reg_1118;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp_i287_fu_818_p2;
reg   [0:0] cmp_i287_reg_1127;
wire   [0:0] cmp12_i_fu_824_p2;
reg   [0:0] cmp12_i_reg_1132;
wire   [0:0] cmp11_i_fu_830_p2;
reg   [0:0] cmp11_i_reg_1137;
wire   [7:0] empty_111_fu_835_p2;
reg   [7:0] empty_111_reg_1142;
reg   [1:0] Sel_reg_1147;
wire    ap_CS_fsm_state3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_ready;
wire   [23:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_ap_vld;
wire   [15:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_ap_vld;
wire   [0:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1_ap_vld;
wire   [0:0] ap_phi_mux_rampVal_3_flag_0_phi_fu_372_p4;
reg   [0:0] rampVal_3_flag_0_reg_368;
wire    ap_CS_fsm_state5;
wire   [0:0] ap_phi_mux_hdata_flag_0_phi_fu_384_p4;
reg   [0:0] hdata_flag_0_reg_380;
wire   [0:0] ap_phi_mux_rampVal_2_flag_0_phi_fu_396_p4;
reg   [0:0] rampVal_2_flag_0_reg_392;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg;
wire    ap_CS_fsm_state4;
reg   [15:0] rampVal_3_new_0_fu_274;
reg   [15:0] rampVal_3_loc_0_fu_270;
reg   [15:0] rampVal_loc_0_fu_266;
reg   [7:0] hBarSel_4_0_loc_0_fu_262;
reg   [15:0] zonePlateVAddr_loc_0_fu_258;
reg   [7:0] vBarSel_loc_0_fu_254;
reg   [7:0] hBarSel_0_loc_0_fu_250;
reg   [15:0] hdata_new_0_fu_246;
reg   [15:0] hdata_loc_0_fu_242;
reg   [7:0] vBarSel_2_loc_0_fu_238;
reg   [7:0] hBarSel_3_0_loc_0_fu_234;
reg   [15:0] rampVal_2_new_0_fu_230;
reg   [15:0] rampVal_2_loc_0_fu_226;
reg   [7:0] vBarSel_3_loc_0_fu_222;
reg   [7:0] hBarSel_5_0_loc_0_fu_218;
reg   [7:0] p_0_2_0_0_0218_lcssa227_fu_210;
reg   [7:0] p_0_1_0_0_0216_lcssa224_fu_206;
reg   [7:0] p_0_0_0_0_0214_lcssa221_fu_202;
wire   [7:0] add_ln750_fu_845_p2;
wire   [0:0] icmp_ln563_fu_799_p2;
reg   [15:0] y_fu_214;
wire   [15:0] add_ln563_fu_804_p2;
wire   [7:0] zext_ln563_fu_727_p1;
wire   [7:0] zext_ln1775_fu_719_p1;
wire   [7:0] zext_ln1664_fu_707_p1;
wire   [7:0] zext_ln1545_fu_691_p1;
wire   [7:0] zext_ln1412_fu_683_p1;
wire   [15:0] zext_ln1257_fu_667_p1;
wire   [13:0] empty_fu_553_p1;
wire   [13:0] add_i_fu_557_p2;
wire   [13:0] add2_i_fu_577_p2;
wire   [9:0] p_cast_fu_583_p4;
wire   [13:0] empty_110_fu_603_p1;
wire   [13:0] add5_i_fu_607_p2;
wire   [9:0] tmp_3_fu_621_p4;
wire   [10:0] barHeight_cast_fu_631_p1;
wire   [16:0] width_val_cast14_fu_549_p1;
wire   [16:0] height_val_cast15_fu_599_p1;
wire   [16:0] zext_ln563_1_fu_814_p1;
wire   [7:0] trunc_ln563_fu_810_p1;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 rampStart = 8'd0;
#0 rampVal_1 = 16'd0;
#0 rampVal = 8'd0;
#0 hBarSel_4_0 = 8'd0;
#0 zonePlateVAddr = 16'd0;
#0 vBarSel = 3'd0;
#0 hBarSel_0 = 3'd0;
#0 hdata = 16'd0;
#0 vBarSel_2 = 8'd0;
#0 hBarSel_3_0 = 3'd0;
#0 rampVal_2 = 16'd0;
#0 vBarSel_1 = 1'd0;
#0 hBarSel_5_0 = 3'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg = 1'b0;
#0 rampVal_3_loc_0_fu_270 = 16'd0;
#0 rampVal_loc_0_fu_266 = 16'd0;
#0 hBarSel_4_0_loc_0_fu_262 = 8'd0;
#0 zonePlateVAddr_loc_0_fu_258 = 16'd0;
#0 vBarSel_loc_0_fu_254 = 8'd0;
#0 hBarSel_0_loc_0_fu_250 = 8'd0;
#0 hdata_loc_0_fu_242 = 16'd0;
#0 vBarSel_2_loc_0_fu_238 = 8'd0;
#0 hBarSel_3_0_loc_0_fu_234 = 8'd0;
#0 rampVal_2_loc_0_fu_226 = 16'd0;
#0 vBarSel_3_loc_0_fu_222 = 8'd0;
#0 hBarSel_5_0_loc_0_fu_218 = 8'd0;
#0 y_fu_214 = 16'd0;
end

design_1_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_din),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write),
    .rampVal_3_flag_0(rampVal_3_flag_0_reg_368),
    .hdata_flag_0(hdata_flag_0_reg_380),
    .rampVal_2_flag_0(rampVal_2_flag_0_reg_392),
    .width_val(width_val),
    .rampStart_1(rampStart_load_reg_1071),
    .ZplateHorContStart_val(ZplateHorContStart_val),
    .patternId_val(patternId_val),
    .conv2_i_i10_i233_cast(rampStart_load_reg_1071),
    .y(y_4_reg_1118),
    .empty_41(empty_109_reg_1083),
    .barWidth_cast(barWidth_reg_1077),
    .barWidth(barWidth_reg_1077),
    .shl_i(shl_i_reg_1093),
    .ZplateHorContDelta_val(ZplateHorContDelta_val),
    .ZplateVerContStart_val(ZplateVerContStart_val),
    .cmp12_i(cmp12_i_reg_1132),
    .ZplateVerContDelta_val(ZplateVerContDelta_val),
    .sub_i_i_i(sub_i_i_i_reg_1098),
    .barWidthMinSamples(barWidthMinSamples_reg_1088),
    .cmp11_i(cmp11_i_reg_1137),
    .cmp_i287(cmp_i287_reg_1127),
    .sub35_i(sub35_i_reg_1103),
    .empty(empty_111_reg_1142),
    .zext_ln565(Sel_reg_1147),
    .cmp121_i(cmp121_i_reg_1113),
    .rampVal_3_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out),
    .rampVal_3_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out_ap_vld),
    .rampVal_3_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out),
    .rampVal_3_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out_ap_vld),
    .rampVal_3_loc_1_out_i(rampVal_3_loc_0_fu_270),
    .rampVal_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o),
    .rampVal_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o_ap_vld),
    .rampVal_loc_1_out_i(rampVal_loc_0_fu_266),
    .rampVal_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o),
    .rampVal_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o_ap_vld),
    .hBarSel_4_0_loc_1_out_i(hBarSel_4_0_loc_0_fu_262),
    .hBarSel_4_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o),
    .hBarSel_4_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o_ap_vld),
    .zonePlateVAddr_loc_1_out_i(zonePlateVAddr_loc_0_fu_258),
    .zonePlateVAddr_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o),
    .zonePlateVAddr_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_254),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o_ap_vld),
    .hBarSel_0_loc_1_out_i(hBarSel_0_loc_0_fu_250),
    .hBarSel_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o),
    .hBarSel_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o_ap_vld),
    .hdata_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out),
    .hdata_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out_ap_vld),
    .hdata_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out),
    .hdata_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out_ap_vld),
    .hdata_loc_1_out_i(hdata_loc_0_fu_242),
    .hdata_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o),
    .hdata_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o_ap_vld),
    .vBarSel_2_loc_1_out_i(vBarSel_2_loc_0_fu_238),
    .vBarSel_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o),
    .vBarSel_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o_ap_vld),
    .hBarSel_3_0_loc_1_out_i(hBarSel_3_0_loc_0_fu_234),
    .hBarSel_3_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o),
    .hBarSel_3_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o_ap_vld),
    .rampVal_2_flag_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out),
    .rampVal_2_flag_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out_ap_vld),
    .rampVal_2_new_1_out(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out),
    .rampVal_2_new_1_out_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out_ap_vld),
    .rampVal_2_loc_1_out_i(rampVal_2_loc_0_fu_226),
    .rampVal_2_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o),
    .rampVal_2_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o_ap_vld),
    .vBarSel_3_loc_1_out_i(vBarSel_3_loc_0_fu_222),
    .vBarSel_3_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o),
    .vBarSel_3_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o_ap_vld),
    .hBarSel_5_0_loc_1_out_i(hBarSel_5_0_loc_0_fu_218),
    .hBarSel_5_0_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o),
    .hBarSel_5_0_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o_ap_vld),
    .p_0_2_0_0_0217_out_i(p_0_2_0_0_0218_lcssa227_fu_210),
    .p_0_2_0_0_0217_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o),
    .p_0_2_0_0_0217_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o_ap_vld),
    .p_0_1_0_0_0215_out_i(p_0_1_0_0_0216_lcssa224_fu_206),
    .p_0_1_0_0_0215_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o),
    .p_0_1_0_0_0215_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o_ap_vld),
    .p_0_0_0_0_0213_out_i(p_0_0_0_0_0214_lcssa221_fu_202),
    .p_0_0_0_0_0213_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o),
    .p_0_0_0_0_0213_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o_ap_vld),
    .rampVal(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal),
    .rampVal_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_ap_vld),
    .hBarSel_4_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0),
    .hBarSel_4_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_ap_vld),
    .zonePlateVAddr(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr),
    .zonePlateVAddr_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_ap_vld),
    .hBarSel_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0),
    .hBarSel_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_ap_vld),
    .hBarSel_3_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0),
    .hBarSel_3_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_ap_vld),
    .vBarSel_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2),
    .vBarSel_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_ap_vld),
    .hBarSel_5_0(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0),
    .hBarSel_5_0_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln563_fu_799_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_0_loc_0_fu_250 <= zext_ln1545_fu_691_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_0_loc_0_fu_250 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_3_0_loc_0_fu_234 <= zext_ln1664_fu_707_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_3_0_loc_0_fu_234 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_4_0_loc_0_fu_262 <= hBarSel_4_0;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_4_0_loc_0_fu_262 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hBarSel_5_0_loc_0_fu_218 <= zext_ln563_fu_727_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_5_0_loc_0_fu_218 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        hdata_flag_0_reg_380 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_flag_1_out;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_flag_0_reg_380 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        hdata_loc_0_fu_242 <= hdata;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_loc_0_fu_242 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_2_flag_0_reg_392 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_flag_1_out;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_flag_0_reg_392 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_2_loc_0_fu_226 <= rampVal_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_loc_0_fu_226 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        rampVal_3_flag_0_reg_368 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_flag_1_out;
    end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_flag_0_reg_368 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_3_loc_0_fu_270 <= rampVal_1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o_ap_vld == 1'b1))) begin
        rampVal_3_loc_0_fu_270 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        rampVal_loc_0_fu_266 <= zext_ln1257_fu_667_p1;
    end else if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o_ap_vld == 1'b1))) begin
        rampVal_loc_0_fu_266 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_2_loc_0_fu_238 <= vBarSel_2;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2_loc_0_fu_238 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_3_loc_0_fu_222 <= zext_ln1775_fu_719_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_3_loc_0_fu_222 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_3_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        vBarSel_loc_0_fu_254 <= zext_ln1412_fu_683_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_loc_0_fu_254 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_214 <= 16'd0;
    end else if (((icmp_ln563_fu_799_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        y_fu_214 <= add_ln563_fu_804_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        zonePlateVAddr_loc_0_fu_258 <= zonePlateVAddr;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr_loc_0_fu_258 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        Sel_reg_1147 <= {{y_4_reg_1118[7:6]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        barWidthMinSamples_reg_1088 <= barWidthMinSamples_fu_593_p2;
        barWidth_reg_1077 <= {{add_i_fu_557_p2[13:3]}};
        cmp121_i_reg_1113 <= cmp121_i_fu_653_p2;
        empty_109_reg_1083 <= empty_109_fu_573_p1;
        rampStart_load_reg_1071 <= rampStart;
        shl_i_reg_1093[15 : 8] <= shl_i_fu_613_p3[15 : 8];
        sub10_i_reg_1108 <= sub10_i_fu_647_p2;
        sub35_i_reg_1103 <= sub35_i_fu_641_p2;
        sub_i_i_i_reg_1098 <= sub_i_i_i_fu_635_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp11_i_reg_1137 <= cmp11_i_fu_830_p2;
        cmp12_i_reg_1132 <= cmp12_i_fu_824_p2;
        cmp_i287_reg_1127 <= cmp_i287_fu_818_p2;
        empty_111_reg_1142 <= empty_111_fu_835_p2;
        y_4_reg_1118 <= y_fu_214;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_3_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_4_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_4_0;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hBarSel_5_0 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hBarSel_5_0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_799_p2 == 1'd1) & (ap_phi_mux_hdata_flag_0_phi_fu_384_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        hdata <= hdata_new_0_fu_246;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        hdata_new_0_fu_246 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_hdata_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_0_0_0_0214_lcssa221_fu_202 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_0_0_0_0213_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_1_0_0_0216_lcssa224_fu_206 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_1_0_0_0215_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        p_0_2_0_0_0218_lcssa227_fu_210 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_p_0_2_0_0_0217_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_799_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampStart <= add_ln750_fu_845_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_799_p2 == 1'd1) & (ap_phi_mux_rampVal_3_flag_0_phi_fu_372_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampVal_1 <= rampVal_3_new_0_fu_274;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_799_p2 == 1'd1) & (ap_phi_mux_rampVal_2_flag_0_phi_fu_396_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        rampVal_2 <= rampVal_2_new_0_fu_230;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        rampVal_2_new_0_fu_230 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_2_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out_ap_vld == 1'b1))) begin
        rampVal_3_new_0_fu_274 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_rampVal_3_new_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_vBarSel_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_zonePlateVAddr;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln563_fu_799_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_799_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_write;
    end else begin
        bckgndYUV_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val7_c21_blk_n = height_val7_c21_full_n;
    end else begin
        height_val7_c21_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val7_c21_write = 1'b1;
    end else begin
        height_val7_c21_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val19_c_blk_n = motionSpeed_val19_c_full_n;
    end else begin
        motionSpeed_val19_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val19_c_write = 1'b1;
    end else begin
        motionSpeed_val19_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val12_c24_blk_n = width_val12_c24_full_n;
    end else begin
        width_val12_c24_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val12_c24_write = 1'b1;
    end else begin
        width_val12_c24_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln563_fu_799_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2_i_fu_577_p2 = (empty_fu_553_p1 + 14'd15);

assign add5_i_fu_607_p2 = (empty_110_fu_603_p1 + 14'd15);

assign add_i_fu_557_p2 = (empty_fu_553_p1 + 14'd7);

assign add_ln563_fu_804_p2 = (y_fu_214 + 16'd1);

assign add_ln750_fu_845_p2 = (rampStart + motionSpeed_val);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((motionSpeed_val19_c_full_n == 1'b0) | (width_val12_c24_full_n == 1'b0) | (height_val7_c21_full_n == 1'b0) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_phi_mux_hdata_flag_0_phi_fu_384_p4 = hdata_flag_0_reg_380;

assign ap_phi_mux_rampVal_2_flag_0_phi_fu_396_p4 = rampVal_2_flag_0_reg_392;

assign ap_phi_mux_rampVal_3_flag_0_phi_fu_372_p4 = rampVal_3_flag_0_reg_368;

assign barHeight_cast_fu_631_p1 = tmp_3_fu_621_p4;

assign barWidthMinSamples_fu_593_p2 = ($signed(p_cast_fu_583_p4) + $signed(10'd1023));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_bckgndYUV_din;

assign cmp11_i_fu_830_p2 = ((sub10_i_reg_1108 == zext_ln563_1_fu_814_p1) ? 1'b1 : 1'b0);

assign cmp121_i_fu_653_p2 = ((dpYUVCoef_val == 8'd0) ? 1'b1 : 1'b0);

assign cmp12_i_fu_824_p2 = ((y_fu_214 != 16'd0) ? 1'b1 : 1'b0);

assign cmp_i287_fu_818_p2 = ((y_fu_214 == 16'd0) ? 1'b1 : 1'b0);

assign empty_109_fu_573_p1 = s[7:0];

assign empty_110_fu_603_p1 = height_val[13:0];

assign empty_111_fu_835_p2 = (rampStart + trunc_ln563_fu_810_p1);

assign empty_fu_553_p1 = width_val[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_404_ap_start_reg;

assign height_val7_c21_din = height_val;

assign height_val_cast15_fu_599_p1 = height_val;

assign icmp_ln563_fu_799_p2 = ((y_fu_214 == height_val) ? 1'b1 : 1'b0);

assign motionSpeed_val19_c_din = motionSpeed_val;

assign p_cast_fu_583_p4 = {{add2_i_fu_577_p2[13:4]}};

assign shl_i_fu_613_p3 = {{rampStart}, {8'd0}};

assign sub10_i_fu_647_p2 = ($signed(height_val_cast15_fu_599_p1) + $signed(17'd131071));

assign sub35_i_fu_641_p2 = ($signed(width_val_cast14_fu_549_p1) + $signed(17'd131071));

assign sub_i_i_i_fu_635_p2 = ($signed(barHeight_cast_fu_631_p1) + $signed(11'd2047));

assign tmp_3_fu_621_p4 = {{add5_i_fu_607_p2[13:4]}};

assign trunc_ln563_fu_810_p1 = y_fu_214[7:0];

assign width_val12_c24_din = width_val;

assign width_val_cast14_fu_549_p1 = width_val;

assign zext_ln1257_fu_667_p1 = rampVal;

assign zext_ln1412_fu_683_p1 = vBarSel;

assign zext_ln1545_fu_691_p1 = hBarSel_0;

assign zext_ln1664_fu_707_p1 = hBarSel_3_0;

assign zext_ln1775_fu_719_p1 = vBarSel_1;

assign zext_ln563_1_fu_814_p1 = y_fu_214;

assign zext_ln563_fu_727_p1 = hBarSel_5_0;

always @ (posedge ap_clk) begin
    shl_i_reg_1093[7:0] <= 8'b00000000;
end

endmodule //design_1_v_tpg_0_0_tpgBackground
