// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module design_1_v_tpg_0_0_v_vcresampler_core (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        stream_out_hresampled_dout,
        stream_out_hresampled_num_data_valid,
        stream_out_hresampled_fifo_cap,
        stream_out_hresampled_empty_n,
        stream_out_hresampled_read,
        height_val7_dout,
        height_val7_num_data_valid,
        height_val7_fifo_cap,
        height_val7_empty_n,
        height_val7_read,
        width_val12_dout,
        width_val12_num_data_valid,
        width_val12_fifo_cap,
        width_val12_empty_n,
        width_val12_read,
        p_read,
        stream_out_vresampled_din,
        stream_out_vresampled_num_data_valid,
        stream_out_vresampled_fifo_cap,
        stream_out_vresampled_full_n,
        stream_out_vresampled_write,
        height_val7_c_din,
        height_val7_c_num_data_valid,
        height_val7_c_fifo_cap,
        height_val7_c_full_n,
        height_val7_c_write,
        width_val12_c_din,
        width_val12_c_num_data_valid,
        width_val12_c_fifo_cap,
        width_val12_c_full_n,
        width_val12_c_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] stream_out_hresampled_dout;
input  [2:0] stream_out_hresampled_num_data_valid;
input  [2:0] stream_out_hresampled_fifo_cap;
input   stream_out_hresampled_empty_n;
output   stream_out_hresampled_read;
input  [15:0] height_val7_dout;
input  [2:0] height_val7_num_data_valid;
input  [2:0] height_val7_fifo_cap;
input   height_val7_empty_n;
output   height_val7_read;
input  [15:0] width_val12_dout;
input  [2:0] width_val12_num_data_valid;
input  [2:0] width_val12_fifo_cap;
input   width_val12_empty_n;
output   width_val12_read;
input  [0:0] p_read;
output  [23:0] stream_out_vresampled_din;
input  [2:0] stream_out_vresampled_num_data_valid;
input  [2:0] stream_out_vresampled_fifo_cap;
input   stream_out_vresampled_full_n;
output   stream_out_vresampled_write;
output  [11:0] height_val7_c_din;
input  [2:0] height_val7_c_num_data_valid;
input  [2:0] height_val7_c_fifo_cap;
input   height_val7_c_full_n;
output   height_val7_c_write;
output  [12:0] width_val12_c_din;
input  [2:0] width_val12_c_num_data_valid;
input  [2:0] width_val12_c_fifo_cap;
input   width_val12_c_full_n;
output   width_val12_c_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg stream_out_hresampled_read;
reg height_val7_read;
reg width_val12_read;
reg stream_out_vresampled_write;
reg height_val7_c_write;
reg width_val12_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    height_val7_blk_n;
wire    ap_CS_fsm_state2;
reg    width_val12_blk_n;
reg    height_val7_c_blk_n;
reg    width_val12_c_blk_n;
reg    ap_block_state1;
reg   [15:0] loopWidth_reg_279;
reg    ap_block_state2;
reg   [15:0] height_val7_read_reg_284;
wire   [15:0] zext_ln2232_fu_180_p1;
reg   [15:0] zext_ln2232_reg_289;
wire   [15:0] loopHeight_fu_184_p2;
reg   [15:0] loopHeight_reg_294;
wire   [0:0] empty_77_fu_213_p1;
reg   [0:0] empty_77_reg_302;
wire    ap_CS_fsm_state3;
wire   [0:0] cmp33_i_fu_217_p2;
reg   [0:0] cmp33_i_reg_307;
wire   [0:0] cmp107_i_fu_222_p2;
reg   [0:0] cmp107_i_reg_312;
reg   [0:0] tmp_reg_317;
wire   [7:0] linebuf_y_q0;
wire   [7:0] linebuf_c_q1;
wire   [7:0] linebuf_c_1_q1;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_idle;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_ready;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read;
wire   [23:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_din;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write;
wire   [11:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_d0;
wire   [11:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address1;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce1;
wire   [11:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_d0;
wire   [11:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce0;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_we0;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_d0;
wire   [11:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address1;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce1;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o_ap_vld;
wire   [7:0] grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o;
wire    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o_ap_vld;
reg    grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg   [7:0] p_0_0324493_lcssa516_i_fu_86;
reg   [7:0] p_0_0335491_lcssa513_i_fu_82;
reg   [7:0] pix_0_2_0_0_0_load489_lcssa510_i_fu_78;
reg   [7:0] pix_0_1_0_0_0_load487_lcssa507_i_fu_74;
reg   [7:0] pix_0_0_0_0_0_load485_lcssa504_i_fu_70;
reg   [14:0] y_fu_90;
wire   [14:0] add_ln2272_fu_202_p2;
wire   [0:0] icmp_ln2272_fu_197_p2;
wire   [0:0] yOffset_fu_175_p2;
wire   [15:0] zext_ln2272_fu_193_p1;
wire   [15:0] out_y_fu_208_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 5'd1;
#0 grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg = 1'b0;
#0 y_fu_90 = 15'd0;
end

design_1_v_tpg_0_0_v_vcresampler_core_linebuf_y_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
linebuf_y_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_d0),
    .q0(linebuf_y_q0)
);

design_1_v_tpg_0_0_v_vcresampler_core_linebuf_c_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
linebuf_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_d0),
    .address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address1),
    .ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce1),
    .q1(linebuf_c_q1)
);

design_1_v_tpg_0_0_v_vcresampler_core_linebuf_c_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
linebuf_c_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address0),
    .ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce0),
    .we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_we0),
    .d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_d0),
    .address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address1),
    .ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce1),
    .q1(linebuf_c_1_q1)
);

design_1_v_tpg_0_0_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2 grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start),
    .ap_done(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done),
    .ap_idle(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_idle),
    .ap_ready(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_ready),
    .stream_out_hresampled_dout(stream_out_hresampled_dout),
    .stream_out_hresampled_num_data_valid(3'd0),
    .stream_out_hresampled_fifo_cap(3'd0),
    .stream_out_hresampled_empty_n(stream_out_hresampled_empty_n),
    .stream_out_hresampled_read(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read),
    .stream_out_vresampled_din(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_din),
    .stream_out_vresampled_num_data_valid(3'd0),
    .stream_out_vresampled_fifo_cap(3'd0),
    .stream_out_vresampled_full_n(stream_out_vresampled_full_n),
    .stream_out_vresampled_write(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write),
    .loopWidth(loopWidth_reg_279),
    .p_read(p_read),
    .cmp33_i(cmp33_i_reg_307),
    .cmp107_i(cmp107_i_reg_312),
    .linebuf_c_1_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address0),
    .linebuf_c_1_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce0),
    .linebuf_c_1_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_we0),
    .linebuf_c_1_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_d0),
    .linebuf_c_1_address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_address1),
    .linebuf_c_1_ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_1_ce1),
    .linebuf_c_1_q1(linebuf_c_1_q1),
    .empty_40(empty_77_reg_302),
    .empty(tmp_reg_317),
    .linebuf_y_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_address0),
    .linebuf_y_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_ce0),
    .linebuf_y_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_we0),
    .linebuf_y_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_y_d0),
    .linebuf_y_q0(linebuf_y_q0),
    .linebuf_c_address0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address0),
    .linebuf_c_ce0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce0),
    .linebuf_c_we0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_we0),
    .linebuf_c_d0(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_d0),
    .linebuf_c_address1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_address1),
    .linebuf_c_ce1(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_linebuf_c_ce1),
    .linebuf_c_q1(linebuf_c_q1),
    .p_0_0324492_i_out_i(p_0_0324493_lcssa516_i_fu_86),
    .p_0_0324492_i_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o),
    .p_0_0324492_i_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o_ap_vld),
    .p_0_0335490_i_out_i(p_0_0335491_lcssa513_i_fu_82),
    .p_0_0335490_i_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o),
    .p_0_0335490_i_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o_ap_vld),
    .pix_0_2_0_0_0_load488_i_out_i(pix_0_2_0_0_0_load489_lcssa510_i_fu_78),
    .pix_0_2_0_0_0_load488_i_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o),
    .pix_0_2_0_0_0_load488_i_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o_ap_vld),
    .pix_0_1_0_0_0_load486_i_out_i(pix_0_1_0_0_0_load487_lcssa507_i_fu_74),
    .pix_0_1_0_0_0_load486_i_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o),
    .pix_0_1_0_0_0_load486_i_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o_ap_vld),
    .pix_0_0_0_0_0_load484_i_out_i(pix_0_0_0_0_0_load485_lcssa504_i_fu_70),
    .pix_0_0_0_0_0_load484_i_out_o(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o),
    .pix_0_0_0_0_0_load484_i_out_o_ap_vld(grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln2272_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg <= 1'b1;
        end else if ((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_ready == 1'b1)) begin
            grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_90 <= 15'd0;
    end else if (((icmp_ln2272_fu_197_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_90 <= add_ln2272_fu_202_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cmp107_i_reg_312 <= cmp107_i_fu_222_p2;
        cmp33_i_reg_307 <= cmp33_i_fu_217_p2;
        empty_77_reg_302 <= empty_77_fu_213_p1;
        tmp_reg_317 <= out_y_fu_208_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        height_val7_read_reg_284 <= height_val7_dout;
        loopHeight_reg_294 <= loopHeight_fu_184_p2;
        loopWidth_reg_279 <= width_val12_dout;
        zext_ln2232_reg_289[0] <= zext_ln2232_fu_180_p1[0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o_ap_vld == 1'b1))) begin
        p_0_0324493_lcssa516_i_fu_86 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0324492_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o_ap_vld == 1'b1))) begin
        p_0_0335491_lcssa513_i_fu_82 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_p_0_0335490_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
        pix_0_0_0_0_0_load485_lcssa504_i_fu_70 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_0_0_0_0_load484_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o_ap_vld == 1'b1))) begin
        pix_0_1_0_0_0_load487_lcssa507_i_fu_74 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_1_0_0_0_load486_i_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o_ap_vld == 1'b1))) begin
        pix_0_2_0_0_0_load489_lcssa510_i_fu_78 <= grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_pix_0_2_0_0_0_load488_i_out_o;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2272_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln2272_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        height_val7_blk_n = height_val7_empty_n;
    end else begin
        height_val7_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        height_val7_c_blk_n = height_val7_c_full_n;
    end else begin
        height_val7_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        height_val7_c_write = 1'b1;
    end else begin
        height_val7_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        height_val7_read = 1'b1;
    end else begin
        height_val7_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        stream_out_hresampled_read = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_hresampled_read;
    end else begin
        stream_out_hresampled_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        stream_out_vresampled_write = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_write;
    end else begin
        stream_out_vresampled_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        width_val12_blk_n = width_val12_empty_n;
    end else begin
        width_val12_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        width_val12_c_blk_n = width_val12_c_full_n;
    end else begin
        width_val12_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        width_val12_c_write = 1'b1;
    end else begin
        width_val12_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
        width_val12_read = 1'b1;
    end else begin
        width_val12_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln2272_fu_197_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln2272_fu_202_p2 = (y_fu_90 + 15'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2 = ((width_val12_c_full_n == 1'b0) | (height_val7_c_full_n == 1'b0) | (width_val12_empty_n == 1'b0) | (height_val7_empty_n == 1'b0));
end

assign cmp107_i_fu_222_p2 = ((y_fu_90 != 15'd0) ? 1'b1 : 1'b0);

assign cmp33_i_fu_217_p2 = ((zext_ln2272_fu_193_p1 < height_val7_read_reg_284) ? 1'b1 : 1'b0);

assign empty_77_fu_213_p1 = out_y_fu_208_p2[0:0];

assign grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_ap_start_reg;

assign height_val7_c_din = height_val7_dout[11:0];

assign icmp_ln2272_fu_197_p2 = (($signed(zext_ln2272_fu_193_p1) < $signed(loopHeight_reg_294)) ? 1'b1 : 1'b0);

assign loopHeight_fu_184_p2 = (height_val7_dout + zext_ln2232_fu_180_p1);

assign out_y_fu_208_p2 = (zext_ln2272_fu_193_p1 - zext_ln2232_reg_289);

assign stream_out_vresampled_din = grp_v_vcresampler_core_Pipeline_VITIS_LOOP_2275_2_fu_138_stream_out_vresampled_din;

assign width_val12_c_din = width_val12_dout[12:0];

assign yOffset_fu_175_p2 = (p_read ^ 1'd1);

assign zext_ln2232_fu_180_p1 = yOffset_fu_175_p2;

assign zext_ln2272_fu_193_p1 = y_fu_90;

always @ (posedge ap_clk) begin
    zext_ln2232_reg_289[15:1] <= 15'b000000000000000;
end

endmodule //design_1_v_tpg_0_0_v_vcresampler_core
